# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_add_import_event_schema_version'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='treeimportrow',
            index_together=set([('import_event', 'idx')]),
        ),
    ]
