# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0046_auto_20170907_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='itree_region_default',
            field=models.CharField(blank=True, choices=[('CaNCCoJBK', 'Northern California Coast'), ('CenFlaXXX', 'Central Florida'), ('GulfCoCHS', 'Coastal Plain'), ('InlEmpCLM', 'Inland Empire'), ('InlValMOD', 'Inland Valleys'), ('InterWABQ', 'Interior West'), ('LoMidWXXX', 'Lower Midwest'), ('MidWstMSP', 'Midwest'), ('NMtnPrFNL', 'North'), ('NoEastXXX', 'Northeast'), ('PacfNWLOG', 'Pacific Northwest'), ('PiedmtCLT', 'South'), ('SoCalCSMA', 'Southern California Coast'), ('SWDsrtGDL', 'Southwest Desert'), ('TpIntWBOI', 'Temperate Interior West'), ('TropicPacXXX', 'Tropical')], max_length=20, null=True),
        ),
    ]
