# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0046_auto_20170907_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='INaturalistObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_id', models.IntegerField()),
                ('map_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.MapFeature')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.Tree')),
            ],
        ),
        migrations.CreateModel(
            name='INaturalistPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inaturalist_photo_id', models.IntegerField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.INaturalistObservation')),
                ('tree_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemap.TreePhoto')),
            ],
        ),
    ]
