# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-01 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0047_auto_20200217_1043'),
        ('treemap', '0047_inaturalistobservation_inaturalistphoto'),
    ]

    operations = [
    ]
