# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-19 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('treemap', '0050_userdefinedfielddefinition_isrequired'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('ward', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Neighborhood',
            },
            bases=('auth.group',),
        ),
        migrations.AlterField(
            model_name='mapfeaturephoto',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='trees-thumbs/%Y/%m/%d'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhoodgroup',
            unique_together=set([('ward', 'neighborhood')]),
        ),
    ]
