# Generated by Django 3.1.7 on 2021-02-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treemap', '0051_auto_20200718_1914'),
        ('treemap', '0047_instance_itree_region_default_choices_to_list'),
    ]

    operations = [
    ]
