# flake8: noqa

def _all_region_codes():
    return _CODES.keys()

def all_species_codes():
    return species_codes_for_regions(_all_region_codes())

def species_codes_for_regions(region_codes):
    if region_codes is None:
        return None
    species_codes = []
    for region_code in region_codes:
        species_codes.extend(_CODES[region_code])
    # Converting to a set removes duplicates
    return list(set(species_codes))

# TODO: this appears not to be used. is it?
def get_itree_code(region_code, otm_code):
    if otm_code:
        if region_code in _CODES:
            if otm_code in _CODES[region_code]:
                return _CODES[region_code][otm_code]
    return None

# The ``_CODES`` dictionary has the following format
#
#   {
#     itree_region_code: {
#       otm_code: itree_code
#     }
#   }
#
# The otm_code of a species is usually the same as a
# USDA code, but this is not guaranteed.
#
# Calculating eco benefits for a tree requires a diameter
# and an itree code. The itree code for a tree is based on
# the species of the tree, but the specific code assigned
# to a species changes depending on where that species
# is located geographically.

_CODES = {
##################################################
    'CaNCCoJBK': {
        'AB': 'CEL OTHER',
        'AC': 'BDM OTHER',
        'ACBA2': 'ACME',
        'ACBU': 'BDS OTHER',
        'ACDE': 'ACME',
        'ACDE2': 'ACME',
        'ACLO': 'ACME',
        'ACMA': 'BDL OTHER',
        'ACME': 'ACME',
        'ACNE': 'BDL OTHER',
        'ACPA': 'ACPA',
        'ACPL': 'BDL OTHER',
        'ACPS': 'BDM OTHER',
        'ACRU': 'BDM OTHER',
        'ACSA1': 'BDL OTHER',
        'ACSA2': 'BDL OTHER',
        'ACVE2': 'ACME',
        'AECA2': 'BES OTHER',
        'AEHI': 'BES OTHER',
        'AGFL': 'BES OTHER',
        'AIAL': 'BDM OTHER',
        'ALAR': 'PES OTHER',
        'ALCO2': 'BDM OTHER',
        'ALJU': 'BDM OTHER',
        'ALRH': 'BDM OTHER',
        'ALRU2': 'BDM OTHER',
        'ARCU': 'PES OTHER',
        'ARHE': 'CEL OTHER',
        'ARME': 'BEM OTHER',
        'ARRO': 'PES OTHER',
        'ARUN': 'BES OTHER',
        'BDL OTHER': 'ULAM',
        'BDM OTHER': 'FRVE',
        'BDS OTHER': 'PRCE',
        'BEAL2': 'BDM OTHER',
        'BEL OTHER': 'QUAG',
        'BEM OTHER': 'CICA',
        'BENI': 'BDM OTHER',
        'BEPE': 'BDM OTHER',
        'BES OTHER': 'PYKA',
        'BR': 'PES OTHER',
        'BRED': 'PES OTHER',
        'BRPA': 'BDM OTHER',
        'BUCA': 'PES OTHER',
        'CABE': 'BDM OTHER',
        'CACA3': 'BDM OTHER',
        'CACI': 'BES OTHER',
        'CADE2': 'CEL OTHER',
        'CAEQ': 'CEL OTHER',
        'CAER': 'BDM OTHER',
        'CAJA9': 'BES OTHER',
        'CALE': 'BES OTHER',
        'CASA5': 'BES OTHER',
        'CASP': 'BDL OTHER',
        'CAVI': 'BES OTHER',
        'CEAT': 'CEL OTHER',
        'CEAU': 'BDL OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEL OTHER': 'PIRA',
        'CEM OTHER': 'PIBR2',
        'CEOC': 'BDL OTHER',
        'CEOC3': 'BDS OTHER',
        'CERE': 'BDS OTHER',
        'CERE2': 'BDS OTHER',
        'CESI3': 'BEM OTHER',
        'CESI4': 'BDL OTHER',
        'CES OTHER': 'PICO5',
        'CETH': 'BES OTHER',
        'CHFU': 'CEL OTHER',
        'CHHU': 'PES OTHER',
        'CHLA2': 'CEL OTHER',
        'CHSP': 'CEL OTHER',
        'CIAU': 'BES OTHER',
        'CICA': 'CICA',
        'CILI': 'BES OTHER',
        'CIPA': 'BES OTHER',
        'CISI': 'BES OTHER',
        'COAU': 'PES OTHER',
        'COBU': 'BES OTHER',
        'COCO1': 'BDS OTHER',
        'CONU2': 'BDM OTHER',
        'CR': 'BDS OTHER',
        'CRDO': 'BDS OTHER',
        'CRPH': 'BDS OTHER',
        'CUAN': 'BES OTHER',
        'CUAR': 'CEM OTHER',
        'CULE': 'CEM OTHER',
        'CUMA': 'CEL OTHER',
        'CUSE': 'CEM OTHER',
        'CYSC4': 'BDS OTHER',
        'DAIM': 'BDS OTHER',
        'DIVI': 'BDS OTHER',
        'DOVI': 'BES OTHER',
        'DRDR': 'PES OTHER',
        'ERDE': 'BES OTHER',
        'ERJA': 'BES OTHER',
        'EU1': 'EUGL',
        'EUCI': 'EUGL',
        'EUCI2': 'EUGL',
        'EUFI81': 'EUGL',
        'EUGL': 'EUGL',
        'EUGU': 'EUGL',
        'EULE': 'EUGL',
        'EULE2': 'EUGL',
        'EUMA': 'EUGL',
        'EUNI': 'EUGL',
        'EUNY': 'BES OTHER',
        'EUPA2': 'BES OTHER',
        'EUPA26': 'EUGL',
        'EUPO': 'EUGL',
        'EURU': 'EUGL',
        'EUSI': 'EUGL',
        'EUSM': 'BES OTHER',
        'EUTO11': 'EUGL',
        'FASY': 'BDL OTHER',
        'FESE': 'BES OTHER',
        'FIBE': 'BEM OTHER',
        'FICA': 'BDS OTHER',
        'FIEL': 'BES OTHER',
        'FIRE4': 'BEM OTHER',
        'FR': 'FRVE',
        'FRAN2': 'FRVE',
        'FRCA6': 'BES OTHER',
        'FRME2': 'BES OTHER',
        'FRUH': 'BDL OTHER',
        'FRVE': 'FRVE',
        'GAEL': 'BES OTHER',
        'GEPA': 'BEM OTHER',
        'GIBI': 'GIBI',
        'GLTR': 'ROPS',
        'GRRO': 'BEL OTHER',
        'HASU': 'CES OTHER',
        'HEAR': 'BES OTHER',
        'HISY': 'BDS OTHER',
        'HYFL': 'BES OTHER',
        'ILAL': 'BES OTHER',
        'ILCO2': 'BES OTHER',
        'JA6': 'BES OTHER',
        'JAMI': 'BDM OTHER',
        'JU': 'CES OTHER',
        'JUCA1': 'CEM OTHER',
        'JUCH': 'CES OTHER',
        'JUNI': 'BDL OTHER',
        'JUOC': 'CEL OTHER',
        'JURE': 'BDM OTHER',
        'KOBI': 'BDM OTHER',
        'KOEL': 'BDM OTHER',
        'LAIN': 'BDS OTHER',
        'LANO': 'BEM OTHER',
        'LAPA': 'BEM OTHER',
        'LELA12': 'BES OTHER',
        'LIDE': 'BEL OTHER',
        'LIFO': 'BDM OTHER',
        'LIJA': 'BES OTHER',
        'LILU': 'BEM OTHER',
        'LIOV': 'BES OTHER',
        'LIST': 'LIST',
        'LITU': 'LITU',
        'LYFL': 'BEM OTHER',
        'LYRA': 'BES OTHER',
        'MA2': 'BDS OTHER',
        'MABO': 'BEM OTHER',
        'MAGR': 'MAGR',
        'MAPU': 'BDS OTHER',
        'MASO': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MASY2': 'BDS OTHER',
        'MATI': 'BDS OTHER',
        'MEAZ': 'BDM OTHER',
        'MEEX': 'BEM OTHER',
        'MEGL': 'BDL OTHER',
        'MELE': 'BEM OTHER',
        'MELI7': 'BES OTHER',
        'MENE': 'BES OTHER',
        'MEQU': 'BEM OTHER',
        'MEST': 'BEM OTHER',
        'MOAL': 'BDM OTHER',
        'MOAR': 'BES OTHER',
        'MUPA3': 'BES OTHER',
        'MYCA': 'BES OTHER',
        'MYLA': 'BES OTHER',
        'NEOL': 'BES OTHER',
        'NIGL': 'BES OTHER',
        'NYSY': 'BDM OTHER',
        'OLEU': 'BEM OTHER',
        'OPFI': 'CES OTHER',
        'OTHER': 'BDM OTHER',
        'PEAM': 'BEM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PH18': 'BES OTHER',
        'PHCA': 'PEL OTHER',
        'PHDA4': 'PEL OTHER',
        'PHFR': 'BES OTHER',
        'PHRO': 'PES OTHER',
        'PI2': 'PIRA',
        'PI23': 'PIUN',
        'PIBR2': 'PIBR2',
        'PICA': 'PIRA',
        'PICE': 'PIRA',
        'PICH': 'PICH',
        'PICO2': 'PIRA',
        'PICO5': 'PICO5',
        'PICR': 'PIUN',
        'PIEU': 'PIUN',
        'PIHA': 'PIRA',
        'PIPA4': 'PIRA',
        'PIPI2': 'PIRA',
        'PIPU': 'CEL OTHER',
        'PIRA': 'PIRA',
        'PIRH': 'PIUN',
        'PITH': 'PIRA',
        'PITO': 'PIUN',
        'PITO2': 'PIRA',
        'PIUN': 'PIUN',
        'PIVI5': 'PIUN',
        'PLAC': 'PLAC',
        'PLRA': 'BDL OTHER',
        'POAL': 'BDL OTHER',
        'POBA': 'BDL OTHER',
        'POFR': 'BDL OTHER',
        'POGR2': 'BEL OTHER',
        'POMA': 'BES OTHER',
        'PONI': 'BDL OTHER',
        'POTR1': 'BDM OTHER',
        'PR': 'BDS OTHER',
        'PRAM2': 'BDS OTHER',
        'PRAR': 'BDS OTHER',
        'PRBL': 'BDS OTHER',
        'PRCA': 'BDS OTHER',
        'PRCE': 'PRCE',
        'PRDO': 'BDS OTHER',
        'PRIL': 'BDS OTHER',
        'PRLY': 'BDS OTHER',
        'PRPE2': 'BDS OTHER',
        'PRPI': 'BDS OTHER',
        'PRSE2': 'BDS OTHER',
        'PRYE': 'BDS OTHER',
        'PSME': 'CEL OTHER',
        'PTTR': 'BDS OTHER',
        'PYCA': 'PYCA',
        'PYCO': 'BDS OTHER',
        'PYIO': 'BDS OTHER',
        'PYKA': 'PYKA',
        'PYSP': 'BES OTHER',
        'QU': 'QUAG',
        'QUAG': 'QUAG',
        'QUCH': 'QUAG',
        'QUCO': 'QUAG',
        'QUIL2': 'QUAG',
        'QUKE': 'QUAG',
        'QULO': 'QUAG',
        'QUPA': 'QUAG',
        'QURO': 'QUAG',
        'QURU': 'QUAG',
        'QUSU': 'QUAG',
        'QUVI': 'QUAG',
        'RHIN2': 'BES OTHER',
        'RHLA': 'BES OTHER',
        'RHOV': 'BES OTHER',
        'RHSP1': 'BES OTHER',
        'ROPS': 'ROPS',
        'SA': 'BDM OTHER',
        'SA12': 'BDS OTHER',
        'SABA': 'BDM OTHER',
        'SACA': 'BDS OTHER',
        'SADI': 'BDS OTHER',
        'SALA1': 'BDS OTHER',
        'SALU': 'BDS OTHER',
        'SAMA': 'BDM OTHER',
        'SC3': 'BES OTHER',
        'SCMO': 'BEM OTHER',
        'SCPO': 'BES OTHER',
        'SCTE': 'BES OTHER',
        'SEGI': 'CEL OTHER',
        'SESE': 'SESE',
        'SETR': 'BDS OTHER',
        'STNI': 'BES OTHER',
        'SYRE': 'BDS OTHER',
        'TABA': 'BES OTHER',
        'TACH2': 'BDS OTHER',
        'TAIM': 'BES OTHER',
        'THOC': 'CEL OTHER',
        'THPL': 'CEL OTHER',
        'TICO': 'BDM OTHER',
        'TIEU': 'BDM OTHER',
        'TIUR': 'BES OTHER',
        'TRCO': 'BEL OTHER',
        'TRFO': 'PES OTHER',
        'TRLA': 'BES OTHER',
        'TRSE6': 'BDM OTHER',
        'ULAM': 'ULAM',
        'ULPA': 'ULPA',
        'ULPU': 'ULAM',
        'UMCA': 'BEL OTHER',
        'VIJA': 'BES OTHER',
        'WAFI': 'PES OTHER',
        'WARO': 'WARO',
        'XYCO': 'BES OTHER',
        'YUAL': 'PES OTHER',
        'YUGL2': 'PES OTHER',
        'YURE': 'PES OTHER',
        'YUTO': 'PES OTHER',
        'ZESE': 'BDL OTHER'
    } # END CaNCCoJBK
    ,
##################################################
    'CenFlaXXX': {
        'ACAC2': 'PES OTHER',
        'ACNE': 'BDM OTHER',
        'ACPA': 'BDS OTHER',
        'ACRU': 'ACRU',
        'ACSP2': 'BEM OTHER',
        'ACWR': 'PES OTHER',
        'ALJU': 'BDS OTHER',
        'ALLE': 'BDL OTHER',
        'ARCU': 'PES OTHER',
        'ARHE': 'CEL OTHER',
        'AVCA': 'BES OTHER',
        'BA': 'BES OTHER',
        'BAVA': 'BEM OTHER',
        'BDL OTHER': 'QULA2',
        'BDM OTHER': 'ULPA',
        'BDS OTHER': 'LAIN',
        'BE': 'BDM OTHER',
        'BEL OTHER': 'MAGR',
        'BEM OTHER': 'CICA',
        'BENI': 'BDM OTHER',
        'BES OTHER': 'ERJA',
        'BIJA': 'BEM OTHER',
        'BINO': 'PES OTHER',
        'BOSP': 'BES OTHER',
        'BRAC': 'BEL OTHER',
        'BRPA': 'BDM OTHER',
        'BRSU': 'BES OTHER',
        'BUCA': 'PES OTHER',
        'CA1': 'BDL OTHER',
        'CABI2': 'BDS OTHER',
        'CACA': 'BDM OTHER',
        'CAEQ': 'BEL OTHER',
        'CAFI': 'BDM OTHER',
        'CAGL': 'BDL OTHER',
        'CAIL': 'BDL OTHER',
        'CAME': 'BES OTHER',
        'CAMI36': 'PES OTHER',
        'CAOV': 'BDL OTHER',
        'CAOV2': 'BDL OTHER',
        'CAPA3': 'BES OTHER',
        'CAPU13': 'BES OTHER',
        'CASSI': 'BDS OTHER',
        'CASU34': 'BES OTHER',
        'CATO': 'BDL OTHER',
        'CAVI': 'BEM OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CELA': 'CEL OTHER',
        'CEL OTHER': 'PIEL2',
        'CEM OTHER': 'JUSI',
        'CES OTHER': 'THOR',
        'CHHU': 'PES OTHER',
        'CHLU': 'PES OTHER',
        'CHSP': 'BDL OTHER',
        'CICA': 'CICA',
        'CISP': 'BES OTHER',
        'CL6': 'BES OTHER',
        'CLQU': 'BES OTHER',
        'COCI': 'BEL OTHER',
        'COFL': 'BDS OTHER',
        'CONU': 'PEL OTHER',
        'COPR': 'PES OTHER',
        'COUV': 'BES OTHER',
        'CUAN': 'BEM OTHER',
        'CUAR': 'CEL OTHER',
        'CULA': 'CEL OTHER',
        'CULE': 'CEM OTHER',
        'CUSE': 'CEM OTHER',
        'CYCI': 'PEM OTHER',
        'CYRE11': 'PES OTHER',
        'DASI': 'BDL OTHER',
        'DERE': 'BDS OTHER',
        'DIVI': 'BDM OTHER',
        'DYDE2': 'PES OTHER',
        'ELDE': 'BEL OTHER',
        'ENCY': 'BDL OTHER',
        'ERCR': 'BEM OTHER',
        'ERJA': 'ERJA',
        'EU1': 'BEL OTHER',
        'EUTI': 'BDS OTHER',
        'EUUN2': 'BEM OTHER',
        'FE': 'BES OTHER',
        'FI1': 'BEM OTHER',
        'FIBE2': 'BEL OTHER',
        'FICA': 'BDS OTHER',
        'FIEL': 'BEL OTHER',
        'FILY': 'BEL OTHER',
        'FRCA': 'BDM OTHER',
        'FRPE': 'BDL OTHER',
        'GIBI': 'BDM OTHER',
        'GLTRIN': 'BDL OTHER',
        'GRRO': 'BEL OTHER',
        'HIMO': 'BDS OTHER',
        'HITI': 'BDM OTHER',
        'HYLA': 'PES OTHER',
        'ILCO2': 'BES OTHER',
        'ILSP': 'BES OTHER',
        'ILVO': 'BES OTHER',
        'JAIN': 'BES OTHER',
        'JAMI': 'BDM OTHER',
        'JU': 'JUSI',
        'JUCH': 'CEL OTHER',
        'JUSI': 'JUSI',
        'KOEL': 'KOELFO',
        'LAIN': 'LAIN',
        'LICH': 'PEM OTHER',
        'LIDE2': 'PEM OTHER',
        'LIJA': 'BES OTHER',
        'LILU': 'BES OTHER',
        'LIOR': 'LIST',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'LOGO': 'BEL OTHER',
        'MAGR': 'MAGR',
        'MAIN': 'BES OTHER',
        'MAPU': 'BDM OTHER',
        'MASO': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MATE': 'BDM OTHER',
        'MAVI': 'MAGR',
        'MEAZ': 'BDM OTHER',
        'MEQU': 'BEL OTHER',
        'MOAL': 'BDM OTHER',
        'MUPA': 'BES OTHER',
        'MYCE': 'BES OTHER',
        'NEOL': 'BES OTHER',
        'NORE': 'PES OTHER',
        'NYSY': 'BDM OTHER',
        'PAAC': 'BDS OTHER',
        'PATO': 'BDM OTHER',
        'PEAM': 'BEL OTHER',
        'PEBO': 'BEL OTHER',
        'PEL OTHER': 'SYRO',
        'PEM OTHER': 'SAPA',
        'PES OTHER': 'WARO',
        'PHCA': 'PEL OTHER',
        'PHDA4': 'PEM OTHER',
        'PHFR': 'BES OTHER',
        'PHRE': 'PEL OTHER',
        'PHRO': 'PES OTHER',
        'PHSP2': 'BES OTHER',
        'PHSY': 'PEM OTHER',
        'PI2': 'CEL OTHER',
        'PICL': 'CEL OTHER',
        'PIEC': 'CEL OTHER',
        'PIEL': 'PIEL2',
        'PIFE': 'BES OTHER',
        'PIPA': 'CEL OTHER',
        'PITA': 'CEL OTHER',
        'PLAC1': 'BDL OTHER',
        'PLOC': 'PLOC',
        'PODE': 'BDL OTHER',
        'POMA': 'BEM OTHER',
        'PONA': 'BEL OTHER',
        'POPI': 'BES OTHER',
        'PR': 'BDS OTHER',
        'PRAN': 'BDS OTHER',
        'PRCA': 'PRCA',
        'PRPE2': 'BDS OTHER',
        'PRSE1': 'BDL OTHER',
        'PYCA': 'BDS OTHER',
        'PYCO': 'BDM OTHER',
        'QU': 'QULA2',
        'QUAC2': 'QULA2',
        'QUAL': 'QULA2',
        'QUFA': 'QULA2',
        'QUGE': 'QUVI',
        'QULA': 'BDS OTHER',
        'QULA2': 'QULA2',
        'QUMI': 'QULA2',
        'QUNI': 'QULA2',
        'QUNU': 'QULA2',
        'QUPH': 'QULA2',
        'QUSH': 'QUSH',
        'QUVI': 'QUVI',
        'RAGL': 'PES OTHER',
        'RHIN62': 'BES OTHER',
        'SABA': 'BDM OTHER',
        'SANI4': 'BDS OTHER',
        'SAPA': 'SAPA',
        'SCTE': 'BDS OTHER',
        'SEPU7': 'BDS OTHER',
        'SIGL': 'BEL OTHER',
        'SWMA': 'BDL OTHER',
        'SYRO': 'SYRO',
        'TAAS': 'BDL OTHER',
        'TACA': 'BEL OTHER',
        'TACH': 'BEL OTHER',
        'TADI': 'BDL OTHER',
        'TAIN': 'BEL OTHER',
        'TAPA': 'BEL OTHER',
        'TASP': 'BDL OTHER',
        'TH9': 'CEL OTHER',
        'THOR': 'THOR',
        'TIGR3': 'BES OTHER',
        'TITI2': 'BDL OTHER',
        'TRSE6': 'TRSE6',
        'ULAL': 'BDL OTHER',
        'ULAM': 'BDL OTHER',
        'ULPA': 'ULPA',
        'ULPU': 'BDL OTHER',
        'ULRU': 'BDM OTHER',
        'ULS': 'BDL OTHER',
        'ULX': 'BDL OTHER',
        'UNP': 'PES OTHER',
        'UNS': 'BDS OTHER',
        'VEME': 'PES OTHER',
        'VIOD': 'BES OTHER',
        'VISP2': 'BES OTHER',
        'WAFI': 'PES OTHER',
        'WARO': 'WARO',
        'WOBI2': 'PEM OTHER',
        'YU1': 'PES OTHER'
    } # END CenFlaXXX
    ,
##################################################
    'GulfCoCHS' : {
        'ACBU': 'ACRU',
        'ACGI': 'ACRU',
        'ACNE': 'ACRU',
        'ACPA': 'ACRU',
        'ACRU': 'ACRU',
        'ACRU_O': 'ACRU',
        'ACSA1': 'ACRU',
        'ACSA2': 'ACRU',
        'AEGL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'BDL OTHER': 'CAIL',
        'BDM OTHER': 'PYCA',
        'BDS OTHER': 'LAIN',
        'BEL OTHER': 'QUVI',
        'BEM OTHER': 'MAGR',
        'BENI': 'BDM OTHER',
        'BES OTHER': 'ILOP',
        'BRPA': 'BDM OTHER',
        'BUCA': 'BUCA',
        'CA1': 'CAIL',
        'CABI': 'BDM OTHER',
        'CACA': 'BDM OTHER',
        'CACO': 'CAIL',
        'CAGL': 'CAIL',
        'CAIL': 'CAIL',
        'CASA': 'BES OTHER',
        'CATO': 'CAIL',
        'CECA': 'BDS OTHER',
        'CELA': 'CELA',
        'CEL OTHER': 'PITA',
        'CEM OTHER': 'JUVI',
        'CES OTHER': 'PICO5',
        'CHHU': 'PES OTHER',
        'CHTH': 'CEL OTHER',
        'CIAU2': 'BES OTHER',
        'CICA': 'BEM OTHER',
        'CLLU': 'BDM OTHER',
        'COFL': 'COFL',
        'COKO': 'COFL',
        'CRPH': 'BDS OTHER',
        'CULE': 'CEL OTHER',
        'CUSE': 'CEM OTHER',
        'CYRE11': 'PES OTHER',
        'DIVI': 'BDM OTHER',
        'ERJA': 'BES OTHER',
        'EUCI': 'BEM OTHER',
        'EUSA': 'BEL OTHER',
        'FISI': 'BDM OTHER',
        'FOIN3': 'BDS OTHER',
        'FRAM': 'BDL OTHER',
        'FRPE': 'BDL OTHER',
        'GIBI': 'BDL OTHER',
        'GLTR': 'GLTR',
        'HIMU3': 'BDS OTHER',
        'HISY': 'BDS OTHER',
        'ILAT': 'ILOP',
        'ILCA': 'ILOP',
        'ILCO2': 'ILOP',
        'ILMY': 'ILOP',
        'ILOP': 'ILOP',
        'ILOP_S': 'ILOP',
        'ILSP': 'ILOP',
        'ILVO': 'ILOP',
        'JU': 'JUVI',
        'JUNI': 'BDL OTHER',
        'JUVI': 'JUVI',
        'KOBI': 'BDM OTHER',
        'KOPA': 'BDS OTHER',
        'LA6_M': 'LAIN',
        'LA6_N': 'LAIN',
        'LA6_T1': 'LAIN',
        'LA6_T2': 'LAIN',
        'LAIN': 'LAIN',
        'LIJA': 'BES OTHER',
        'LISI': 'BES OTHER',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'MA2': 'BDS OTHER',
        'MAGR': 'MAGR',
        'MAGR_L': 'BEM OTHER',
        'MASO': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MATR': 'BDS OTHER',
        'MEAZ': 'BDM OTHER',
        'MEGL': 'CEL OTHER',
        'MORU': 'BDM OTHER',
        'MYCE2': 'BES OTHER',
        'NEOL': 'BES OTHER',
        'NYSY': 'BDL OTHER',
        'OSFR': 'BES OTHER',
        'PAAC': 'BDS OTHER',
        'PEBO': 'BEL OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'SAPA',
        'PES OTHER': 'BUCA',
        'PHCA': 'PHCA',
        'PHFR': 'BES OTHER',
        'PHSE': 'BES OTHER',
        'PHSP2': 'BES OTHER',
        'PICH': 'BDM OTHER',
        'PICO5': 'PICO5',
        'PIEC': 'PITA',
        'PIEL': 'PITA',
        'PINI': 'JUVI',
        'PIPA': 'PITA',
        'PIPU': 'PITA',
        'PIST': 'PITA',
        'PITA': 'PITA',
        'PIVI': 'JUVI',
        'PLAC': 'PLOC',
        'PLAC_B': 'PLOC',
        'PLOC': 'PLOC',
        'POAL': 'BDL OTHER',
        'PODE': 'BDL OTHER',
        'POMA': 'BEM OTHER',
        'PR': 'BDS OTHER',
        'PRAM': 'BDS OTHER',
        'PRCA': 'BEM OTHER',
        'PRCE': 'BDS OTHER',
        'PRPE2': 'BDS OTHER',
        'PRSE1': 'BDL OTHER',
        'PRSE2': 'BDS OTHER',
        'PYAN': 'BDS OTHER',
        'PYCA': 'PYCA',
        'PYCA_B': 'PYCA',
        'PYCO': 'PYCA',
        'PYCO2': 'BES OTHER',
        'QU': 'BDL OTHER',
        'QUAC': 'BDM OTHER',
        'QUAL': 'BDL OTHER',
        'QUCI': 'BES OTHER',
        'QUCO': 'BDL OTHER',
        'QUFA': 'BDL OTHER',
        'QUHE': 'BEM OTHER',
        'QULA1': 'BDM OTHER',
        'QULA2': 'QULA2',
        'QUMI': 'BDL OTHER',
        'QUNI': 'QUNI',
        'QUPA': 'BDL OTHER',
        'QUPH': 'QUPH',
        'QURU': 'BDL OTHER',
        'QUSH': 'BDL OTHER',
        'QUST': 'BDL OTHER',
        'QUVE': 'BDL OTHER',
        'QUVI': 'QUVI',
        'ROPS': 'BDM OTHER',
        'SA': 'BDM OTHER',
        'SAAL': 'BDL OTHER',
        'SAMA_T': 'BDM OTHER',
        'SAMI8': 'PES OTHER',
        'SANI': 'BDM OTHER',
        'SAPA': 'SAPA',
        'SAPE12': 'BDM OTHER',
        'SEBI5': 'BDS OTHER',
        'TADI': 'CEL OTHER',
        'THOC': 'CEM OTHER',
        'TIAM': 'BDL OTHER',
        'TICO': 'BDM OTHER',
        'TRFO': 'PEM OTHER',
        'TRSE6': 'BDM OTHER',
        'ULAL': 'BDM OTHER',
        'ULAM': 'BDL OTHER',
        'ULPA': 'BDM OTHER',
        'ULPA_D': 'BDM OTHER',
        'ULPA_E': 'BDM OTHER',
        'ULPU': 'BDM OTHER',
        'ULRU': 'BDL OTHER',
        'ULS': 'BDL OTHER',
        'VIAG': 'BDS OTHER',
        'VIPR': 'BDS OTHER',
        'WARO': 'PES OTHER',
        'WIFL': 'BDS OTHER',
        'YUGL2': 'PES OTHER',
        'ZESE': 'BDL OTHER'
    } # END GulfCoCHS
    ,
##################################################
    'InlEmpCLM': {
        'ABPR': 'CEL OTHER',
        'ACBA2': 'BEM OTHER',
        'ACDE': 'BEM OTHER',
        'ACLO': 'BEM OTHER',
        'ACMA': 'BDL OTHER',
        'ACME': 'BEM OTHER',
        'ACOB': 'BEM OTHER',
        'ACPA': 'BDL OTHER',
        'ACRU': 'BDL OTHER',
        'ACSA1': 'BDL OTHER',
        'AECA2': 'BES OTHER',
        'AECA3': 'BDS OTHER',
        'AGFL': 'BES OTHER',
        'AIAL': 'BDM OTHER',
        'ALCO2': 'BDM OTHER',
        'ALGL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'ALRH': 'BDM OTHER',
        'ARCU': 'PES OTHER',
        'ARHE': 'CEL OTHER',
        'ARMA2': 'BES OTHER',
        'ARRO': 'PES OTHER',
        'ARUN': 'BES OTHER',
        'BAFO': 'BDS OTHER',
        'BAVA': 'BDS OTHER',
        'BDL OTHER': 'FRUH',
        'BDM OTHER': 'PYCA',
        'BDS OTHER': 'LAIN',
        'BEL OTHER': 'CICA',
        'BEM OTHER': 'MAGR',
        'BEPE': 'BDM OTHER',
        'BES OTHER': 'SCTE',
        'BRAC2': 'BDM OTHER',
        'BRAR': 'PES OTHER',
        'BRBR': 'PES OTHER',
        'BRDI9': 'BDM OTHER',
        'BRED': 'PES OTHER',
        'BRPO': 'BRPO',
        'BUCA': 'PES OTHER',
        'CACA3': 'BEM OTHER',
        'CACI': 'BES OTHER',
        'CADE': 'BDL OTHER',
        'CADE2': 'CEL OTHER',
        'CAED': 'BEL OTHER',
        'CAIL': 'BDL OTHER',
        'CALE': 'BES OTHER',
        'CASP': 'BDL OTHER',
        'CATW': 'BES OTHER',
        'CAVI': 'BES OTHER',
        'CEAT': 'CEL OTHER',
        'CEAU': 'BDL OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEFL': 'BDM OTHER',
        'CEL OTHER': 'PICA',
        'CEM OTHER': 'PIBR2',
        'CEOC': 'BDL OTHER',
        'CEOC3': 'BDS OTHER',
        'CESI3': 'BEM OTHER',
        'CESI4': 'BDL OTHER',
        'CES OTHER': 'PICO5',
        'CHHU': 'PES OTHER',
        'CHLI': 'BDS OTHER',
        'CHRE': 'BDS OTHER',
        'CHSP': 'BEM OTHER',
        'CHTA': 'BDS OTHER',
        'CICA': 'CICA',
        'CILI': 'BES OTHER',
        'CISI': 'BES OTHER',
        'COAU': 'PES OTHER',
        'COLA': 'BES OTHER',
        'CRPA': 'BES OTHER',
        'CRRU': 'BES OTHER',
        'CUAN': 'BES OTHER',
        'CUAR': 'CEM OTHER',
        'CULE': 'CES OTHER',
        'CUSE': 'CEL OTHER',
        'DIVI': 'BDS OTHER',
        'DOVI': 'BES OTHER',
        'ELDE': 'BDS OTHER',
        'ERCA': 'BEL OTHER',
        'ERDE': 'BES OTHER',
        'ERJA': 'BES OTHER',
        'EUCA1': 'EUSI',
        'EUCI': 'EUSI',
        'EUCI2': 'EUSI',
        'EUCL': 'EUSI',
        'EUCO3': 'EUSI',
        'EUCR': 'EUSI',
        'EUFI81': 'EUSI',
        'EUGL': 'EUSI',
        'EUGLCO': 'EUSI',
        'EUGR': 'EUSI',
        'EULE': 'EUSI',
        'EULE2': 'EUSI',
        'EUMA23': 'EUSI',
        'EUNI': 'EUSI',
        'EUPO': 'EUSI',
        'EURO': 'EUSI',
        'EURU': 'EUSI',
        'EUSI': 'EUSI',
        'EUTE': 'EUSI',
        'EUTO11': 'EUSI',
        'EUVI': 'EUSI',
        'FICA': 'BDS OTHER',
        'FIMA2': 'BEL OTHER',
        'FIMINI': 'BES OTHER',
        'FISI': 'BDS OTHER',
        'FRANR': 'FRUH',
        'FROR2': 'FRUH',
        'FRUH': 'FRUH',
        'FRVE': 'FRUH',
        'FRVEG': 'FRVEG',
        'GEPA': 'BES OTHER',
        'GIBI': 'GIBI',
        'GLTR': 'BDM OTHER',
        'GRRO': 'BEL OTHER',
        'HASU': 'CES OTHER',
        'HEAR': 'BES OTHER',
        'HYFL': 'BES OTHER',
        'ILAL': 'BES OTHER',
        'ILVO': 'BES OTHER',
        'JAMI': 'JAMI',
        'JUCA2': 'BDL OTHER',
        'JUCH': 'CES OTHER',
        'JURE': 'BDM OTHER',
        'KOBI': 'BDM OTHER',
        'KOEL': 'BDM OTHER',
        'KOPA': 'BDS OTHER',
        'LAIN': 'LAIN',
        'LANO': 'BEM OTHER',
        'LELA12': 'BES OTHER',
        'LIFO': 'LIST',
        'LILU': 'BEM OTHER',
        'LIOV': 'BES OTHER',
        'LIST': 'LIST',
        'LITU': 'LITU',
        'LYAS': 'BEM OTHER',
        'MA2': 'BDS OTHER',
        'MABO': 'BEM OTHER',
        'MAFL80': 'BDS OTHER',
        'MAGR': 'MAGR',
        'MALA6': 'BDS OTHER',
        'MASO': 'MAGR',
        'MASY2': 'BDS OTHER',
        'MATE': 'BES OTHER',
        'MATI': 'BDS OTHER',
        'MEAZ': 'BDM OTHER',
        'MEGL': 'BDL OTHER',
        'MELI7': 'BES OTHER',
        'MEQU': 'BEM OTHER',
        'MOAL': 'BDL OTHER',
        'MORU': 'BDM OTHER',
        'NEOL': 'BES OTHER',
        'OLEU': 'BES OTHER',
        'OLEU2': 'BES OTHER',
        'PAAC': 'BDM OTHER',
        'PEAM': 'BDS OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PEL OTHER',
        'PHDA4': 'PEM OTHER',
        'PHFR': 'BES OTHER',
        'PHRO': 'PEM OTHER',
        'PIAT': 'CEL OTHER',
        'PIBR2': 'PIBR2',
        'PICA': 'PICA',
        'PICH': 'PICH',
        'PICO2': 'CEL OTHER',
        'PICO5': 'PICO5',
        'PIED': 'CES OTHER',
        'PIEL2': 'CEL OTHER',
        'PIHA': 'CEL OTHER',
        'PIMU2': 'CEM OTHER',
        'PINI': 'CEL OTHER',
        'PIPH2': 'BES OTHER',
        'PIPI2': 'CEL OTHER',
        'PIPU': 'CEL OTHER',
        'PIRA': 'CEL OTHER',
        'PIRH': 'BEM OTHER',
        'PIRO': 'CEL OTHER',
        'PITA': 'CEL OTHER',
        'PITH': 'CES OTHER',
        'PITO': 'BEM OTHER',
        'PITO2': 'CEL OTHER',
        'PIUN': 'BEM OTHER',
        'PIVI5': 'BEM OTHER',
        'PLAC': 'PLAC',
        'PLOC': 'PLRA',
        'PLRA': 'PLRA',
        'POCA2': 'BDL OTHER',
        'POGR2': 'BEL OTHER',
        'POMA': 'BES OTHER',
        'PONI': 'BDL OTHER',
        'PRAR': 'BDS OTHER',
        'PRBL': 'BDS OTHER',
        'PRCA': 'BES OTHER',
        'PRCE': 'BDS OTHER',
        'PRCEKV': 'BDS OTHER',
        'PRCH': 'BDM OTHER',
        'PRDO': 'BDS OTHER',
        'PRDU': 'BDS OTHER',
        'PRIL': 'BDS OTHER',
        'PRLY': 'BDS OTHER',
        'PRPE2': 'BDS OTHER',
        'PRSE2': 'BDS OTHER',
        'PSME': 'CEL OTHER',
        'PTST': 'BDL OTHER',
        'PUGR': 'BDS OTHER',
        'PYCA': 'PYCA',
        'PYCAA': 'PYCA',
        'PYCA_B': 'PYCA',
        'PYKA': 'BES OTHER',
        'QUAG': 'QUAG',
        'QUCO': 'QUAG',
        'QUEN': 'QUAG',
        'QUIL2': 'QUIL2',
        'QUKE': 'QUAG',
        'QULO': 'QUAG',
        'QUPA': 'QUAG',
        'QURO': 'QUAG',
        'QURU': 'QUAG',
        'QUSU': 'QUAG',
        'QUVI': 'QUAG',
        'RHIN': 'BDS OTHER',
        'ROAMI': 'BDM OTHER',
        'ROPS': 'BDL OTHER',
        'SAALT': 'BDL OTHER',
        'SACANE': 'BDS OTHER',
        'SAMA': 'BDL OTHER',
        'SCMO': 'SCMO',
        'SCPO': 'SCMO',
        'SCTE': 'SCTE',
        'SECO9': 'BES OTHER',
        'SEGI': 'CEL OTHER',
        'SESE': 'CEL OTHER',
        'SOJA': 'BDM OTHER',
        'STSI': 'BES OTHER',
        'SYPA2': 'BEM OTHER',
        'TAAV': 'BES OTHER',
        'TACH3': 'BES OTHER',
        'THOC': 'CEL OTHER',
        'THOR': 'CES OTHER',
        'TRAC': 'PES OTHER',
        'TRCO': 'BES OTHER',
        'TRFO': 'PES OTHER',
        'TRSE6': 'BDM OTHER',
        'ULAM': 'BDL OTHER',
        'ULPA': 'BEL OTHER',
        'ULPU': 'BEL OTHER',
        'UMCA': 'BEL OTHER',
        'WAFI': 'PES OTHER',
        'WARO': 'WARO',
        'XYCO': 'PES OTHER',
        'YUGL2': 'PES OTHER',
        'YUGU': 'PES OTHER',
        'ZESE': 'BDL OTHER',
        'ZESE_V': 'BDL OTHER'
    } # END InlEmpCLM
    ,
##################################################
    'InlValMOD': {
        'AC': 'ACSA1',
        'ACBU': 'ACSA1',
        'ACNE': 'ACSA1',
        'ACPA': 'ACSA1',
        'ACPL': 'ACSA1',
        'ACPL_CK': 'ACSA1',
        'ACPS_S': 'ACSA1',
        'ACRU': 'ACSA1',
        'ACSA1': 'ACSA1',
        'ACSP2': 'BEL OTHER',
        'AECA3_B': 'BDM OTHER',
        'AECA3_S': 'BDM OTHER',
        'AIAL': 'BDM OTHER',
        'ALJU': 'BDM OTHER',
        'ALRH': 'BDM OTHER',
        'ARRO': 'PES OTHER',
        'BDL OTHER': 'CESI4',
        'BDM OTHER': 'PYCA_B',
        'BDS OTHER': 'LAIN',
        'BEL OTHER': 'QUIL2',
        'BEM OTHER': 'CICA',
        'BEPE': 'BEPE',
        'BES OTHER': 'PYKA',
        'BRED': 'PEM OTHER',
        'BRPA': 'BDS OTHER',
        'CABE': 'BDM OTHER',
        'CABE_F': 'BDM OTHER',
        'CACI': 'BES OTHER',
        'CADE2': 'CEL OTHER',
        'CAIL': 'BDL OTHER',
        'CE2': 'BDL OTHER',
        'CEAT': 'CEL OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEL OTHER': 'PIRA',
        'CEM OTHER': 'PIBR2',
        'CEOC': 'BDL OTHER',
        'CEOC3': 'BDS OTHER',
        'CESI2': 'BDS OTHER',
        'CESI3': 'BDL OTHER',
        'CESI4': 'CESI4',
        'CES OTHER': 'PICO5',
        'CHLI': 'BDS OTHER',
        'CICA': 'CICA',
        'CISP': 'BES OTHER',
        'COFL': 'BES OTHER',
        'CR': 'BDS OTHER',
        'CRLA80': 'BDS OTHER',
        'CRPH': 'BDS OTHER',
        'CU': 'CEL OTHER',
        'CULE': 'CEL OTHER',
        'CUMA': 'CEL OTHER',
        'CUSE': 'CEL OTHER',
        'DIKA': 'BDM OTHER',
        'ELAN': 'BDS OTHER',
        'ERDE': 'BES OTHER',
        'ERJA': 'BES OTHER',
        'EU1': 'BEL OTHER',
        'EUPO': 'BEL OTHER',
        'FASY': 'BDL OTHER',
        'FICA': 'BDS OTHER',
        'FRAM': 'FRVE_G',
        'FRAM_A': 'FRVE_G',
        'FRAM_R': 'FRVE_G',
        'FRAN_R': 'FRAN_R',
        'FREX': 'FRVE_G',
        'FREXH': 'FREX_H',
        'FREX_K': 'FREX_H',
        'FRHO': 'FRHO',
        'FROX_F': 'FRAN_R',
        'FRPE': 'FRPE_M',
        'FRPEM': 'FRPE_M',
        'FRPE_P': 'FRPE_M',
        'FRPES': 'FRPE_M',
        'FRUH': 'FRPE_M',
        'FRVE': 'FRVE_G',
        'FRVE_FW': 'FRVE_G',
        'FRVEG': 'FRVE_G',
        'GIBI': 'GIBI',
        'GIBI_AG': 'GIBI',
        'GIBI_F': 'GIBI',
        'GL3': 'GLTR',
        'GLTR': 'GLTR',
        'GLTRS1': 'GLTR',
        'GRRO': 'BEL OTHER',
        'HISY': 'BDS OTHER',
        'JU1': 'BDL OTHER',
        'JUHI': 'BDL OTHER',
        'JUNI': 'BDL OTHER',
        'KOPA': 'KOPA',
        'KOPA_F': 'KOPA',
        'LAIN': 'LAIN',
        'LANO': 'BEM OTHER',
        'LIFO': 'LIST',
        'LILU': 'BES OTHER',
        'LIST': 'LIST',
        'LITU': 'LIST',
        'MA1': 'MAGR',
        'MA2': 'BDS OTHER',
        'MABO': 'BEM OTHER',
        'MAFL80': 'BDS OTHER',
        'MAGR': 'MAGR',
        'MASO': 'MAGR',
        'MASO_G': 'MAGR',
        'MEAZ': 'BDM OTHER',
        'MOAL': 'BDM OTHER',
        'NEOL': 'BES OTHER',
        'NYSY': 'BDM OTHER',
        'OLEU': 'BEM OTHER',
        'OSVI': 'BDM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PHFR': 'BES OTHER',
        'PHSE': 'BES OTHER',
        'PHSP2': 'BES OTHER',
        'PI1': 'CEL OTHER',
        'PI2': 'CEL OTHER',
        'PI23': 'BES OTHER',
        'PIAT4': 'PICH',
        'PIBR2': 'PIBR2',
        'PICH': 'PICH',
        'PICH_PS': 'PICH',
        'PICO5': 'PICO5',
        'PINI': 'CEM OTHER',
        'PIPA4': 'CEL OTHER',
        'PIPI2': 'CEL OTHER',
        'PIPU': 'CEL OTHER',
        'PIRA': 'PIRA',
        'PISY': 'CEL OTHER',
        'PITH': 'PITH',
        'PIUN': 'BES OTHER',
        'PLAC': 'PLAC',
        'PLAC_B': 'PLAC',
        'PLAC_C': 'PLAC',
        'PLOC': 'PLAC',
        'PLOR': 'PLAC',
        'PO': 'BDL OTHER',
        'POGR2': 'BEL OTHER',
        'PR': 'BDS OTHER',
        'PRAM2': 'BDS OTHER',
        'PRAR': 'BDM OTHER',
        'PRAV': 'BDM OTHER',
        'PRBL': 'BDS OTHER',
        'PRCE': 'BDS OTHER',
        'PRPE2': 'BDS OTHER',
        'PRSU': 'BDS OTHER',
        'PUGR': 'BDS OTHER',
        'PY': 'BDM OTHER',
        'PYCAA': 'BDM OTHER',
        'PYCA_B': 'PYCA_B',
        'PYCA_C': 'BDM OTHER',
        'PYCA_CH': 'BDM OTHER',
        'PYCA_R': 'BDM OTHER',
        'PYCA_T': 'BDM OTHER',
        'PYCA_W': 'BDM OTHER',
        'PYKA': 'PYKA',
        'QU': 'BEL OTHER',
        'QUAG': 'BEL OTHER',
        'QUCO': 'BEL OTHER',
        'QUIL2': 'QUIL2',
        'QULO': 'BEL OTHER',
        'QUPA': 'BEL OTHER',
        'QURU': 'BEL OTHER',
        'QUSU': 'BEL OTHER',
        'QUWI': 'BEL OTHER',
        'RHLA': 'BES OTHER',
        'ROPS': 'GLTR',
        'ROPS_PR': 'GLTR',
        'SA': 'BDM OTHER',
        'SAMA': 'BDS OTHER',
        'SAPE12': 'BDL OTHER',
        'SCMO': 'BEM OTHER',
        'SEGI': 'CEL OTHER',
        'SESE': 'CEL OTHER',
        'SOHUCF': 'BDS OTHER',
        'SOHUCQ': 'BDS OTHER',
        'SOJA': 'PICH',
        'TADI': 'CEL OTHER',
        'TI': 'BDM OTHER',
        'TRFO': 'PEM OTHER',
        'TRLA': 'BES OTHER',
        'TRLA_E': 'BES OTHER',
        'TRSE6': 'BDM OTHER',
        'ULPA': 'ZESE',
        'ULS': 'ZESE',
        'UMCA': 'BEL OTHER',
        'WAFI': 'PES OTHER',
        'WARO': 'WARO',
        'ZESE': 'ZESE',
        'ZESE_V': 'ZESE'
    } # END InlValMOD
    ,
##################################################
    'InterWABQ': {
        'ACNE': 'BDL OTHER',
        'ACPL': 'BDL OTHER',
        'ACSA1': 'BDL OTHER',
        'AIAL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'BDL OTHER': 'FRAM',
        'BDM OTHER': 'FRAN2',
        'BDS OTHER': 'KOPA',
        'BEL OTHER': 'EUGL',
        'BEM OTHER': 'EUMI2',
        'BES OTHER': 'ILOP',
        'CA3': 'BDL OTHER',
        'CASP': 'BDL OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEL OTHER': 'PIPO',
        'CEM OTHER': 'PINI',
        'CERE2': 'BDS OTHER',
        'CESI4': 'BDM OTHER',
        'CES OTHER': 'PIED',
        'CH31': 'BDS OTHER',
        'CHLI': 'CHLI',
        'CR': 'BDS OTHER',
        'CUAR': 'CEM OTHER',
        'CULE': 'CEL OTHER',
        'ELAN': 'ELAN',
        'EUGL': 'EUGL',
        'EUMI2': 'EUMI2',
        'FOPU2': 'BDS OTHER',
        'FRAM': 'FRAM',
        'FRAN2': 'FRAN2',
        'FRBE': 'FRVE',
        'FRPE': 'FRPE',
        'FRPE2': 'FRPE',
        'FRPEM': 'FRPE',
        'FRVE': 'FRVE',
        'FRVEG': 'FRVE',
        'GLTR': 'GLTR',
        'GYDI': 'BDL OTHER',
        'ILOP': 'ILOP',
        'JU': 'CEM OTHER',
        'JUSC': 'CES OTHER',
        'KOPA': 'KOPA',
        'MA1': 'BES OTHER',
        'MA2': 'BDS OTHER',
        'MAPO': 'BDM OTHER',
        'MO': 'BDM OTHER',
        'OTHER': 'BDM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PI1': 'CEL OTHER',
        'PICH': 'PICH',
        'PIED': 'PIED',
        'PIEL2': 'CEL OTHER',
        'PIFL': 'CEM OTHER',
        'PINI': 'PINI',
        'PIPO': 'PIPO',
        'PIST2': 'CEL OTHER',
        'PISY': 'PISY',
        'PLAC': 'PLAC',
        'PLWR': 'BDL OTHER',
        'PO': 'POAN',
        'POAN': 'POAN',
        'POFR': 'POFR',
        'PR': 'PRCE',
        'PRCE': 'PRCE',
        'PY': 'PYCA',
        'PYCA': 'PYCA',
        'QU': 'BDL OTHER',
        'QUMA1': 'BDL OTHER',
        'QUSH': 'BDL OTHER',
        'ROPS': 'BDL OTHER',
        'SAMA': 'BDL OTHER',
        'SO': 'BDS OTHER',
        'SOJA': 'BDL OTHER',
        'TI': 'BDL OTHER',
        'ULAM': 'ULPU',
        'ULPA': 'ULPU',
        'ULPU': 'ULPU',
        'VI5': 'BDS OTHER',
        'WARO': 'WARO',
        'ZESE': 'ULPU'
    } # END InterWABQ
    ,
##################################################
    'LoMidWXXX': {
        'AB': 'CEL OTHER',
        'ABBA': 'CEL OTHER',
        'ABCO': 'CEL OTHER',
        'ABFR': 'CEL OTHER',
        'AC': 'ACRU',
        'ACCA': 'ACRU',
        'ACCAQE': 'ACRU',
        'ACGI': 'ACRU',
        'ACNE': 'ACRU',
        'ACNI': 'ACPL',
        'ACPA': 'ACRU',
        'ACPL': 'ACPL',
        'ACPLC': 'ACPL',
        'ACPLCK': 'ACPL',
        'ACPS': 'ACPL',
        'ACRU': 'ACRU',
        'ACRUA': 'ACRU',
        'ACRUG': 'ACRU',
        'ACRUOG': 'ACRU',
        'ACRURS': 'ACRU',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'AE': 'BDM OTHER',
        'AEGL': 'BDM OTHER',
        'AEHI': 'BDL OTHER',
        'AIAL': 'BDL OTHER',
        'ALGL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'AMCA': 'BDS OTHER',
        'AMUT': 'BDS OTHER',
        'ARSP': 'BDS OTHER',
        'ASTR': 'BDS OTHER',
        'BDL OTHER': 'FRPE',
        'BDM OTHER': 'TICO',
        'BDS OTHER': 'CECA',
        'BE': 'BDM OTHER',
        'BEAL': 'BDL OTHER',
        'BEL OTHER': 'QUIL2',
        'BEM OTHER': 'MAGR',
        'BENI': 'BDL OTHER',
        'BEPA': 'BDL OTHER',
        'BES OTHER': 'ILOP',
        'BUSP': 'BES OTHER',
        'CA40': 'BDM OTHER',
        'CABEF': 'BDM OTHER',
        'CACA': 'BDM OTHER',
        'CACO': 'BDL OTHER',
        'CAGL': 'BDL OTHER',
        'CALA': 'BDL OTHER',
        'CAMO': 'BDM OTHER',
        'CAOV': 'BDL OTHER',
        'CASP': 'CASP',
        'CECA': 'CECA',
        'CEJA': 'BDL OTHER',
        'CEL OTHER': 'PIST',
        'CEM OTHER': 'PINI',
        'CEOC': 'CEOC',
        'CES OTHER': 'PICO5',
        'CLLU': 'BDM OTHER',
        'CO1': 'BDS OTHER',
        'COAM': 'BDS OTHER',
        'COCO1': 'BDS OTHER',
        'COFL': 'BDS OTHER',
        'CORA': 'BDS OTHER',
        'CR': 'BDS OTHER',
        'CRCRI': 'BDS OTHER',
        'CRLA': 'BDS OTHER',
        'CRPH': 'BDS OTHER',
        'CRVI2': 'BDS OTHER',
        'DIVI': 'BDM OTHER',
        'EL1': 'BDS OTHER',
        'ELAN': 'BDS OTHER',
        'ELUM': 'BES OTHER',
        'EUSP': 'BDS OTHER',
        'EUUL': 'BDM OTHER',
        'FA': 'BDL OTHER',
        'FAGR': 'BDL OTHER',
        'FASY': 'BDL OTHER',
        'FASYP': 'BDL OTHER',
        'FR': 'FRPE',
        'FRAM': 'FRAM',
        'FRAMAA': 'FRAM',
        'FRAMCC': 'FRAM',
        'FREXH': 'FRAM',
        'FRNI': 'FRAM',
        'FROR': 'FRPE',
        'FROXA': 'FRPE',
        'FRPE': 'FRPE',
        'FRPES': 'FRPE',
        'FRQU': 'FRPE',
        'GIBI': 'BDL OTHER',
        'GIBIF2': 'BDL OTHER',
        'GLTR': 'GLTR',
        'GLTRI': 'GLTR',
        'GLTRS': 'GLTR',
        'GLTRS1': 'GLTR',
        'GYDI': 'BDL OTHER',
        'HISP': 'BDS OTHER',
        'ILOP': 'ILOP',
        'JU': 'CES OTHER',
        'JU1': 'JUNI',
        'JUCI': 'JUNI',
        'JUCO3': 'CES OTHER',
        'JUNI': 'JUNI',
        'JUPR': 'CES OTHER',
        'JURE': 'JUNI',
        'JUVI': 'CEM OTHER',
        'KOPA': 'BDS OTHER',
        'LA10': 'BDL OTHER',
        'LADE': 'BDL OTHER',
        'LISP': 'BES OTHER',
        'LIST': 'BDL OTHER',
        'LITU': 'BDL OTHER',
        'LOSP': 'BDS OTHER',
        'MA1': 'BDS OTHER',
        'MA2': 'MA2',
        'MAAC': 'BDL OTHER',
        'MAGR': 'MAGR',
        'MAPO': 'BDL OTHER',
        'MAPY': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MEGL': 'BDL OTHER',
        'MO': 'MO',
        'NYSY': 'BDM OTHER',
        'OSVI': 'BDM OTHER',
        'OXAR': 'BDL OTHER',
        'PA19': 'BDL OTHER',
        'PATO': 'BDM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHAM': 'BDM OTHER',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PI1': 'PIPU',
        'PI2': 'CEL OTHER',
        'PIAB': 'PIPU',
        'PIBA': 'CEL OTHER',
        'PICO5': 'PICO5',
        'PIGL1': 'PIPU',
        'PIMA': 'PIPU',
        'PIMU': 'CES OTHER',
        'PINI': 'PINI',
        'PIPO': 'CEL OTHER',
        'PIPU': 'PIPU',
        'PIRE': 'CEL OTHER',
        'PIRU': 'PIPU',
        'PIST': 'PIST',
        'PISY': 'CEL OTHER',
        'PIVI': 'CEL OTHER',
        'PL3': 'BDL OTHER',
        'PLAC': 'BDL OTHER',
        'PLOC': 'BDL OTHER',
        'PO': 'PODE',
        'POAL': 'PODE',
        'PODE': 'PODE',
        'PONI': 'PODE',
        'PR': 'BDS OTHER',
        'PRHAJO': 'BDS OTHER',
        'PRPE1': 'BDS OTHER',
        'PRSE1': 'BDL OTHER',
        'PRSE2': 'BDS OTHER',
        'PRSU': 'BDS OTHER',
        'PSME': 'CEL OTHER',
        'PY': 'PYCA',
        'PYCA': 'PYCA',
        'PYCAA': 'PYCA',
        'PYCA_B': 'PYCA',
        'QU': 'QURU',
        'QUAL': 'QURU',
        'QUBI': 'QURU',
        'QUCO': 'QURU',
        'QUIL2': 'QUIL2',
        'QUIM': 'QURU',
        'QUMA1': 'QURU',
        'QUMU': 'QURU',
        'QUPA': 'QURU',
        'QUPR': 'QURU',
        'QURO': 'QURU',
        'QUROF': 'QURU',
        'QURU': 'QURU',
        'QUVE': 'QURU',
        'RHCA': 'BDS OTHER',
        'RHFR': 'BDS OTHER',
        'RHTR': 'BDS OTHER',
        'ROPS': 'BDL OTHER',
        'ROVI': 'BDS OTHER',
        'SA': 'BDM OTHER',
        'SAAL': 'BDM OTHER',
        'SOAL': 'BDM OTHER',
        'SOJA': 'BDM OTHER',
        'SPVA2': 'BDS OTHER',
        'SYSP': 'BDS OTHER',
        'TA': 'CES OTHER',
        'TACA': 'CES OTHER',
        'TADI': 'BDL OTHER',
        'THOC': 'CEM OTHER',
        'TI': 'TICO',
        'TIAM': 'BDL OTHER',
        'TICO': 'TICO',
        'TICOG': 'TICO',
        'TITO': 'TICO',
        'TITOSS': 'TICO',
        'TSCA': 'CEM OTHER',
        'ULAM': 'ULPU',
        'ULPA': 'ULPU',
        'ULPU': 'ULPU',
        'ULRU': 'ULPU',
        'ULS': 'ULPU',
        'VISP2': 'BDS OTHER',
        'WARO': 'WARO',
        'ZESE': 'BDL OTHER'
    } # END LoMidWXXX
    ,
##################################################
    'MidWstMSP' : {
        'AC': 'ACRU',
        'ACGI': 'MA2',
        'ACNE': 'ACNE',
        'ACNI': 'ACRU',
        'ACPA': 'BDS OTHER',
        'ACPL': 'ACPL',
        'ACRU': 'ACRU',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'AEGL': 'ACPL',
        'AL': 'MA2',
        'ALJU': 'BDS OTHER',
        'BDL OTHER': 'FRPE',
        'BDM OTHER': 'ACPL',
        'BDS OTHER': 'MA2',
        'BE': 'ACPL',
        'BEL OTHER': 'QUNI',
        'BEM OTHER': 'MAGR',
        'BENI': 'ACPL',
        'BEPA': 'FRPE',
        'BES OTHER': 'ILOP',
        'CA1': 'FRPE',
        'CA3': 'FRPE',
        'CADE': 'BDL OTHER',
        'CASP': 'BDL OTHER',
        'CECA': 'BDS OTHER',
        'CEL OTHER': 'PIPO',
        'CEM OTHER': 'PINI',
        'CEOC': 'CEOC',
        'CES OTHER': 'PICO5',
        'CLLU': 'BDM OTHER',
        'CO1': 'BDS OTHER',
        'COFL': 'BDS OTHER',
        'FR': 'ACPL',
        'FRAM': 'FRAM',
        'FRNI': 'ACPL',
        'FRPE': 'FRPE',
        'GIBI': 'GIBI',
        'GLTR': 'GLTR',
        'GYDI': 'FRPE',
        'HISY': 'BDS OTHER',
        'ILOP': 'BES OTHER',
        'ILSP': 'BES OTHER',
        'JU': 'PICO5',
        'JUNI': 'FRPE',
        'JUVI': 'CES OTHER',
        'LIST': 'BDL OTHER',
        'LITU': 'BDL OTHER',
        'MA2': 'MA2',
        'MAGR': 'BEM OTHER',
        'MAVI': 'BES OTHER',
        'MO': 'MA2',
        'MOAL': 'BDS OTHER',
        'OSVI': 'MA2',
        'PHAM': 'ACPL',
        'PI1': 'PIPO',
        'PIAB': 'CEL OTHER',
        'PICO': 'PICO5',
        'PIMA': 'PINI',
        'PINI': 'PINI',
        'PIPO': 'PIPO',
        'PIPU': 'PINI',
        'PIRE': 'PIPO',
        'PIST': 'PIPO',
        'PISY': 'PIPO',
        'PIVI': 'CEL OTHER',
        'PLOC': 'BDL OTHER',
        'PO': 'FRPE',
        'PODE': 'FRPE',
        'PONI': 'BDL OTHER',
        'POTR1': 'FRPE',
        'PR': 'MA2',
        'PRCE': 'BDS OTHER',
        'PRSE1': 'BDS OTHER',
        'PRSE2': 'BDS OTHER',
        'PRVI': 'MA2',
        'PY': 'MA2',
        'PYCA': 'BDM OTHER',
        'QU': 'FRPE',
        'QUAL': 'FRPE',
        'QUBI': 'ACPL',
        'QUCO': 'BDL OTHER',
        'QUEL': 'ACPL',
        'QUMA1': 'FRPE',
        'QUNI': 'QUNI',
        'QUPA': 'QUPA',
        'QURU': 'QURU',
        'RHSP': 'MA2',
        'RHSP2': 'MA2',
        'ROPS': 'ACPL',
        'SA': 'ACPL',
        'SADI': 'BDS OTHER',
        'SO': 'MA2',
        'SYRE': 'MA2',
        'SYSP': 'MA2',
        'THOC': 'CEL OTHER',
        'TI': 'FRPE',
        'TIAM': 'TIAM',
        'TICO': 'TICO',
        'TSCA': 'CEL OTHER',
        'ULAM': 'ULAM',
        'ULPA': 'BDL OTHER',
        'ULPU': 'ULPU',
        'ULS': 'FRPE',
    } # END MidWstMSP
    ,
##################################################
    'NMtnPrFNL': {
        'ABBA': 'CEL OTHER',
        'ABCO': 'PIPU',
        'AC': 'FRPE',
        'ACFR': 'FRPE',
        'ACGI': 'BDS OTHER',
        'ACGL': 'FRPE',
        'ACNE': 'FRPE',
        'ACPL': 'ACPL',
        'ACRU': 'BDL OTHER',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'ACTA': 'BDS OTHER',
        'AEGL': 'ACPL',
        'AEHI': 'ACPL',
        'AM': 'MA2',
        'BDL OTHER': 'FRPE',
        'BDM OTHER': 'ACPL',
        'BDS OTHER': 'MA2',
        'BE': 'ACPL',
        'BEL OTHER': 'QUNI',
        'BEM OTHER': 'MAGR',
        'BENI': 'BDL OTHER',
        'BEPA': 'BDL OTHER',
        'BEPE': 'BDL OTHER',
        'BES OTHER': 'ILOP',
        'CA1': 'FRPE',
        'CA3': 'FRPE',
        'CABE': 'ACPL',
        'CAOV': 'FRPE',
        'CASP': 'BDL OTHER',
        'CECA': 'MA2',
        'CEL OTHER': 'PIPU',
        'CEM OTHER': 'PINI',
        'CEOC': 'CEOC',
        'CES OTHER': 'PICO5',
        'CO1': 'MA2',
        'COCO2': 'ACPL',
        'CR': 'MA2',
        'ELAN': 'MA2',
        'FA': 'FRPE',
        'FASY': 'FRPE',
        'FR': 'FRPE',
        'FRAM': 'FRAM',
        'FRPE': 'FRPE',
        'GIBI': 'FRPE',
        'GLTR': 'GLTR',
        'GYDI': 'GYDI',
        'ILOP': 'ILOP',
        'JU': 'PICO5',
        'JUCI': 'FRPE',
        'JUCO1': 'PICO5',
        'JUMO': 'PICO5',
        'JUNI': 'FRPE',
        'JUSC': 'PICO5',
        'JUVI': 'PICO5',
        'LIST': 'FRPE',
        'LITU': 'FRPE',
        'LOSP': 'MA2',
        'MA2': 'MA2',
        'MAGR': 'MAGR',
        'MAPU': 'BDM OTHER',
        'MEGL': 'FRPE',
        'MORU': 'BDL OTHER',
        'PI1': 'PIPU',
        'PI2': 'CEM OTHER',
        'PIAB': 'CEL OTHER',
        'PICE': 'PICO5',
        'PICO': 'PINI',
        'PICO5': 'PICO5',
        'PIED': 'PICO5',
        'PIEN': 'PIPU',
        'PIFL': 'CEL OTHER',
        'PIGL1': 'PIPU',
        'PIMA': 'PIPU',
        'PIMU': 'PICO5',
        'PINI': 'PINI',
        'PIPO': 'PIPO',
        'PIPU': 'PIPU',
        'PIRU': 'PIPU',
        'PIST': 'CEL OTHER',
        'PIST2': 'PICO5',
        'PISY': 'PINI',
        'PO': 'FRPE',
        'POAC5': 'FRPE',
        'POAL': 'FRPE',
        'POAN': 'FRPE',
        'POBA': 'BDL OTHER',
        'POCA2': 'FRPE',
        'POFR': 'BDL OTHER',
        'PONI': 'BDL OTHER',
        'POSA': 'POSA',
        'POTR1': 'ACPL',
        'PR': 'PR',
        'PRCE': 'BDS OTHER',
        'PRPA': 'MA2',
        'PRVI': 'MA2',
        'PSME': 'PIPU',
        'PY': 'PY',
        'QU': 'FRPE',
        'QUBI': 'FRPE',
        'QUCO': 'FRPE',
        'QUMA1': 'QUMA1',
        'QUMU': 'FRPE',
        'QUNI': 'QUNI',
        'QUPA': 'FRPE',
        'QURO': 'FRPE',
        'QURU': 'FRPE',
        'QUSH': 'FRPE',
        'RHCA': 'BDS OTHER',
        'RHGL': 'BDS OTHER',
        'RHSP': 'MA2',
        'RHTY': 'MA2',
        'ROPS': 'FRPE',
        'SA': 'FRPE',
        'SAAL4': 'FRPE',
        'SADI': 'MA2',
        'SAFR': 'FRPE',
        'SO': 'MA2',
        'SOAM': 'BDS OTHER',
        'SOAU': 'BDS OTHER',
        'SYRE': 'MA2',
        'SYSP': 'MA2',
        'TH9': 'PIPU',
        'THPL': 'PIPU',
        'TI': 'FRPE',
        'TIAM': 'TIAM',
        'TICO': 'TICO',
        'ULAM': 'ULAM',
        'ULPA': 'BDL OTHER',
        'ULPU': 'ULPU',
        'ULS': 'FRPE',
        'WISI': 'MA2'
    } # END NMtnPrFNL
    ,
##################################################
    'NoEastXXX': {
        'AB': 'CEL OTHER',
        'ABBA': 'CEL OTHER',
        'ABCO': 'CEL OTHER',
        'ABHO': 'CEL OTHER',
        'AC': 'ACPL',
        'ACBU': 'ACPL',
        'ACCA': 'ACPL',
        'ACGI': 'ACPL',
        'ACNE': 'ACPL',
        'ACPA': 'ACPL',
        'ACPE': 'ACPL',
        'ACPL': 'ACPL',
        'ACPLCO': 'ACPL',
        'ACPLCR': 'ACPL',
        'ACPLSC': 'ACPL',
        'ACPS': 'ACPL',
        'ACRU': 'ACRU',
        'ACRUAR': 'ACRU',
        'ACRUOC': 'ACRU',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'ACSA2GR': 'ACSA2',
        'AECA': 'AEHI',
        'AEHI': 'AEHI',
        'AEOC': 'AEHI',
        'AIAL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'AM': 'BDS OTHER',
        'AMAR': 'BDS OTHER',
        'AMCA': 'BDS OTHER',
        'ARAR': 'CEL OTHER',
        'AREX': 'CEL OTHER',
        'ASTR': 'BDS OTHER',
        'BDL OTHER': 'ZESE',
        'BDM OTHER': 'ACRU',
        'BDS OTHER': 'PRSE2',
        'BE': 'BDM OTHER',
        'BEAL': 'BDL OTHER',
        'BELE': 'BDL OTHER',
        'BEL OTHER': 'ULPA99',
        'BEM OTHER': 'MAGR',
        'BENI': 'BDL OTHER',
        'BEPA': 'BDL OTHER',
        'BEPE': 'BDM OTHER',
        'BEPEGR': 'BDM OTHER',
        'BEPO': 'BDM OTHER',
        'BES OTHER': 'ILOP',
        'BRPA': 'BDM OTHER',
        'BUCA': 'BUCA',
        'CA1': 'BDL OTHER',
        'CABE': 'BDM OTHER',
        'CABI': 'BDM OTHER',
        'CACA': 'BDM OTHER',
        'CACO': 'BDL OTHER',
        'CADE': 'BDL OTHER',
        'CAEQ': 'CEL OTHER',
        'CAGL': 'BDL OTHER',
        'CAJA': 'BDM OTHER',
        'CAMO': 'BDM OTHER',
        'CAOV': 'BDL OTHER',
        'CAPU': 'BDS OTHER',
        'CASP': 'BDM OTHER',
        'CATE': 'BDL OTHER',
        'CATO': 'BDL OTHER',
        'CEAT': 'CEM OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEJA': 'BDM OTHER',
        'CEL OTHER': 'PIST',
        'CEM OTHER': 'JUVI',
        'CEOC': 'BDL OTHER',
        'CES OTHER': 'PICO5',
        'CHTH': 'CEM OTHER',
        'CISP': 'BES OTHER',
        'CLLU': 'BDM OTHER',
        'CO1': 'BDS OTHER',
        'CO2': 'BDS OTHER',
        'COCO2': 'BDL OTHER',
        'COFL': 'BDS OTHER',
        'COKO': 'BDS OTHER',
        'COMA': 'BDS OTHER',
        'CR': 'BDS OTHER',
        'CRCR': 'BDS OTHER',
        'CRJA': 'CEL OTHER',
        'CRMO2': 'BDS OTHER',
        'CRPH': 'BDS OTHER',
        'CRVI': 'BDS OTHER',
        'CULE': 'CEL OTHER',
        'DIVI': 'BDM OTHER',
        'ELAN': 'BDS OTHER',
        'ELUM': 'BES OTHER',
        'EUUL': 'BDL OTHER',
        'FA': 'BDL OTHER',
        'FAGR': 'BDL OTHER',
        'FASY': 'BDL OTHER',
        'FR': 'FRPE',
        'FRAM': 'FRPE',
        'FRCA': 'FRPE',
        'FRNI': 'FRPE',
        'FRPE': 'FRPE',
        'FRPES': 'FRPE',
        'GIBI': 'GIBI',
        'GIBI(F)': 'GIBI',
        'GLTR': 'GLTR',
        'GYDI': 'BDL OTHER',
        'HADI': 'BDS OTHER',
        'HAVI': 'BDS OTHER',
        'HISY': 'BDS OTHER',
        'ILCA': 'BES OTHER',
        'ILOP': 'ILOP',
        'ILSP': 'BES OTHER',
        'JUCI': 'BDL OTHER',
        'JUNI': 'BDL OTHER',
        'JURE': 'BDL OTHER',
        'JUVI': 'JUVI',
        'KOEL': 'BDS OTHER',
        'KOPA': 'BDS OTHER',
        'LADE': 'BDL OTHER',
        'LISP': 'BES OTHER',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'MA1': 'BEM OTHER',
        'MA2': 'MA2',
        'MAAM': 'BDM OTHER',
        'MADE': 'BDS OTHER',
        'MAGR': 'MAGR',
        'MAHA': 'MA2',
        'MAIS': 'MA2',
        'MAPU': 'MA2',
        'MASO': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MEGL': 'BDL OTHER',
        'MOAL': 'BDM OTHER',
        'MORU': 'BDM OTHER',
        'MYCE': 'BES OTHER',
        'NYSY': 'BDM OTHER',
        'OSVI': 'BDM OTHER',
        'PATO': 'BDM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'SAPA',
        'PES OTHER': 'BUCA',
        'PHAM': 'BDM OTHER',
        'PHCA': 'PHCA',
        'PI1': 'CEL OTHER',
        'PI2': 'CEL OTHER',
        'PIAB': 'CEL OTHER',
        'PIBA': 'CEM OTHER',
        'PICL': 'CEM OTHER',
        'PICO5': 'PICO5',
        'PIEC': 'CEL OTHER',
        'PIGL1': 'CEL OTHER',
        'PIGL2': 'CEL OTHER',
        'PIMA': 'CEL OTHER',
        'PINI': 'CEL OTHER',
        'PIPUGL': 'CEL OTHER',
        'PIRI': 'CEL OTHER',
        'PISE': 'CEL OTHER',
        'PIST': 'PIST',
        'PISY': 'CEL OTHER',
        'PITA': 'CEL OTHER',
        'PITH': 'CEL OTHER',
        'PLAC': 'PLAC',
        'PLOC': 'PLAC',
        'PO': 'BDL OTHER',
        'POAL': 'BDL OTHER',
        'POBA': 'BDL OTHER',
        'POCA': 'BDL OTHER',
        'PODE': 'BDL OTHER',
        'POGR': 'BDL OTHER',
        'PONI': 'BDL OTHER',
        'PONIIT': 'BDL OTHER',
        'POTR1': 'BDL OTHER',
        'POTR2': 'BDL OTHER',
        'PR': 'PRSE2',
        'PR2': 'PES OTHER',
        'PRAM': 'PRSE2',
        'PRAV': 'PRSE2',
        'PRCA': 'PRSE2',
        'PRCE': 'PRSE2',
        'PRCI': 'PRSE2',
        'PRMA': 'PRSE2',
        'PRPE1': 'PRSE2',
        'PRPE2': 'PRSE2',
        'PRSA': 'PRSE2',
        'PRSE1': 'PRSE2',
        'PRSE2': 'PRSE2',
        'PRSU': 'PRSE2',
        'PRTR': 'PRSE2',
        'PRVI': 'PRSE2',
        'PRVISH': 'PRSE2',
        'PRYE': 'PRSE2',
        'PSME': 'CEL OTHER',
        'PTTR': 'BDS OTHER',
        'PYCA': 'PYCA',
        'PYCAA': 'PYCA',
        'PYCO': 'PYCA',
        'QU': 'QUPA',
        'QUAC': 'QUPA',
        'QUAL': 'QUPA',
        'QUAU': 'QUPA',
        'QUBI': 'QUPA',
        'QUCO': 'QUPA',
        'QUEL': 'QUPA',
        'QUFA': 'QUPA',
        'QUIM': 'QUPA',
        'QULY': 'QUPA',
        'QUMA1': 'QUPA',
        'QUMA2': 'QUPA',
        'QUMU': 'QUPA',
        'QUNI': 'QUPA',
        'QUPA': 'QUPA',
        'QUPAFA': 'QUPA',
        'QUPH': 'QUPH',
        'QUPR': 'QURU',
        'QURO': 'QURU',
        'QURU': 'QURU',
        'QUSH': 'QURU',
        'QUST': 'QURU',
        'QUVE': 'QURU',
        'QUVI': 'QURU',
        'RHGL': 'BDS OTHER',
        'RHTY': 'BDS OTHER',
        'ROPS': 'BDL OTHER',
        'SA': 'BDM OTHER',
        'SAAL': 'BDM OTHER',
        'SABA': 'BDM OTHER',
        'SAMA': 'BDM OTHER',
        'SANI': 'BDM OTHER',
        'SAPA': 'SAPA',
        'SESE': 'CEL OTHER',
        'SOAM': 'BDS OTHER',
        'SOAU': 'BDS OTHER',
        'SOJA': 'BDM OTHER',
        'STJA': 'BDM OTHER',
        'SYRE': 'BDS OTHER',
        'TA': 'CES OTHER',
        'TADI': 'BDL OTHER',
        'THOC': 'CEM OTHER',
        'TI': 'TITO',
        'TIAM': 'TITO',
        'TICO': 'TICO',
        'TICOG': 'TICO',
        'TIPL': 'TITO',
        'TITO': 'TITO',
        'TSCA': 'CEM OTHER',
        'ULAL': 'ULAM',
        'ULAM': 'ULAM',
        'ULCAHO': 'ULAM',
        'ULPA': 'ULAM',
        'ULPA99': 'ULPA99',
        'ULPR': 'ULAM',
        'ULPU': 'ULAM',
        'ULRU': 'ULAM',
        'ULS': 'ULAM',
        'ULSE': 'ULAM',
        'ULTH': 'ULAM',
        'ZE': 'ZESE',
        'ZESE': 'ZESE',
    } # END NoEastXXX
    ,
##################################################
    'PacfNWLOG': {
        'ABGR': 'CEL OTHER',
        'ABLA': 'CEL OTHER',
        'ABMA': 'CEL OTHER',
        'ABPI': 'CES OTHER',
        'ABPR': 'CEL OTHER',
        'AC': 'ACPL',
        'ACBU': 'ACPL',
        'ACCI': 'ACPL',
        'ACMA': 'ACMA',
        'ACNE': 'ACMA',
        'ACPA': 'ACPL',
        'ACPADI': 'ACPL',
        'ACPL': 'ACPL',
        'ACPLFA': 'ACPL',
        'ACPLQE': 'ACPL',
        'ACPLSC': 'ACPL',
        'ACPS': 'ACPL',
        'ACRU': 'ACRU',
        'ACRUMO': 'ACRU',
        'ACSA1': 'ACPL',
        'ACSA2': 'ACSA2',
        'AEHI': 'BDL OTHER',
        'AIAL': 'BDM OTHER',
        'ALJU': 'BDM OTHER',
        'ALRU2': 'BDM OTHER',
        'BDL OTHER': 'ACMA',
        'BDM OTHER': 'TICO',
        'BDS OTHER': 'PRSE2',
        'BEL OTHER': 'QUAG',
        'BEM OTHER': 'ILOP',
        'BENI': 'BEPE',
        'BEPE': 'BEPE',
        'BES OTHER': 'PYKA',
        'CABEF': 'CABEF',
        'CACA3': 'BDM OTHER',
        'CADE2': 'CADE2',
        'CAIL': 'BDL OTHER',
        'CASP': 'BDL OTHER',
        'CEAT': 'CEL OTHER',
        'CEDE': 'CEL OTHER',
        'CEJA': 'BDM OTHER',
        'CEL OTHER': 'PSME',
        'CEM OTHER': 'CADE2',
        'CEOC': 'BDL OTHER',
        'CESI4': 'BDM OTHER',
        'CES OTHER': 'PICO5',
        'CHLA2': 'CEL OTHER',
        'CHNO': 'CEL OTHER',
        'CHOB': 'CES OTHER',
        'CHPI': 'CES OTHER',
        'CHTH': 'CES OTHER',
        'COFL': 'BDS OTHER',
        'COMA2': 'BDS OTHER',
        'CONU2': 'BDM OTHER',
        'CRDO': 'CRLA80',
        'CRLA': 'CRLA80',
        'CRLA80': 'CRLA80',
        'CRPH': 'CRLA80',
        'CULA': 'CEM OTHER',
        'FASY': 'FASYAT',
        'FASYAT': 'FASYAT',
        'FRAM': 'FRLA',
        'FRHO': 'FRLA',
        'FRLA': 'FRLA',
        'FROX': 'FRLA',
        'FRPEM': 'FRLA',
        'FRPESG': 'FRLA',
        'FRVE': 'FRLA',
        'GIBI': 'BDL OTHER',
        'GLTR': 'BDL OTHER',
        'ILAQ': 'ILOP',
        'ILOP': 'ILOP',
        'JUCH': 'CES OTHER',
        'JURE': 'BDM OTHER',
        'KOPA': 'BDM OTHER',
        'LAAN2': 'BDS OTHER',
        'LADE': 'BDM OTHER',
        'LADEWPE': 'BDS OTHER',
        'LIOR': 'BDM OTHER',
        'LIST': 'BDM OTHER',
        'LITU': 'BDL OTHER',
        'MAFL80': 'PYAN',
        'MAGR': 'BES OTHER',
        'MAIO': 'PYAN',
        'MAMA': 'BDM OTHER',
        'MAPUEL': 'PYAN',
        'MASO': 'BDS OTHER',
        'MASY2': 'PYAN',
        'MOAL': 'MOAL',
        'PAPE': 'BDM OTHER',
        'PATO': 'BDM OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PHFR': 'BES OTHER',
        'PIAB': 'CEL OTHER',
        'PIAR': 'CES OTHER',
        'PICO': 'PICO5',
        'PICO5': 'PICO5',
        'PICO6': 'PICO5',
        'PIDE': 'CEL OTHER',
        'PIGL1': 'CEL OTHER',
        'PIMU': 'CADE2',
        'PIPI2': 'CADE2',
        'PIPO': 'CEL OTHER',
        'PIPU': 'CEL OTHER',
        'PISI': 'CEL OTHER',
        'PISY': 'CEL OTHER',
        'PITH': 'CEL OTHER',
        'PLAC': 'ACMA',
        'POAL': 'POTR2',
        'POALPY': 'POTR2',
        'PONI': 'POTR2',
        'POTR1': 'POTR2',
        'POTR2': 'POTR2',
        'PRAV': 'PRSE2',
        'PRBL': 'PRSE2',
        'PRCE': 'PRCEKW',
        'PRCEKW': 'PRCEKW',
        'PRDO': 'PRSE2',
        'PRLA': 'PRSE2',
        'PRPE2': 'PRSE2',
        'PRSE2': 'PRSE2',
        'PRSEAM': 'PRSE2',
        'PRSESH': 'PRSE2',
        'PRSESO': 'PRSE2',
        'PRSU': 'PRSE2',
        'PRYE': 'BDM OTHER',
        'PSME': 'PSME',
        'PYAN': 'PYAN',
        'PYCACL': 'PYKA',
        'PYCO': 'PYKA',
        'PYKA': 'PYKA',
        'QUAG': 'QUAG',
        'QUAL': 'QURU',
        'QUCO': 'QURU',
        'QUMA1': 'QURU',
        'QUPA': 'QURU',
        'QURU': 'QURU',
        'RHGL': 'BDS OTHER',
        'RHTY': 'BDS OTHER',
        'ROPS': 'BDM OTHER',
        'SAAM': 'BDM OTHER',
        'SABA': 'BDM OTHER',
        'SACANE': 'BDS OTHER',
        'SAMA': 'BDM OTHER',
        'SASC': 'BDM OTHER',
        'SCVE': 'PSME',
        'SEGI': 'PSME',
        'SESE': 'PSME',
        'SOAU': 'BDS OTHER',
        'SYRE': 'BDS OTHER',
        'SYVU': 'BDS OTHER',
        'TABA': 'CES OTHER',
        'TABR': 'PSME',
        'TADI': 'BDL OTHER',
        'THOC': 'PSME',
        'THPL': 'PSME',
        'TIAM': 'TIAM',
        'TICO': 'TICO',
        'TIHE': 'TIAM',
        'TSHE': 'PSME',
        'TSME': 'CES OTHER',
        'ULAM': 'ULAM',
        'ULAMLI': 'ULAM',
        'ULPR': 'ULAM',
        'ULPU': 'ULAM',
        'WARO': 'WARO',
        'WISI': 'BDS OTHER'
    } # END PacfNWLOG
    ,
##################################################
    'PiedmtCLT': {
        'AB': 'CEL OTHER',
        'ABCO': 'CEL OTHER',
        'ACBA2': 'BES OTHER',
        'ACBU': 'BDS OTHER',
        'ACCA': 'BDM OTHER',
        'ACFR': 'BDL OTHER',
        'ACGI': 'BDS OTHER',
        'ACGR': 'BDS OTHER',
        'ACMA': 'BDL OTHER',
        'ACNE': 'BDM OTHER',
        'ACNI': 'BDL OTHER',
        'ACPA': 'BDS OTHER',
        'ACPL': 'BDL OTHER',
        'ACRU': 'ACRU',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'ACTR': 'BDS OTHER',
        'AEFL': 'BDL OTHER',
        'AEGL': 'BDL OTHER',
        'AEHI': 'BDL OTHER',
        'AEPA': 'BDS OTHER',
        'AIAL': 'BDL OTHER',
        'ALJU': 'BDS OTHER',
        'AM': 'BDS OTHER',
        'AMAR': 'BDS OTHER',
        'ARAR': 'CEL OTHER',
        'ASTR': 'BDS OTHER',
        'AU1': 'BES OTHER',
        'BDL OTHER': 'ACSA2',
        'BDM OTHER': 'BENI',
        'BDS OTHER': 'COFL',
        'BELE': 'BDM OTHER',
        'BEL OTHER': 'QUNI',
        'BEM OTHER': 'MAGR',
        'BENI': 'BENI',
        'BEPA': 'BDM OTHER',
        'BEPE': 'BDM OTHER',
        'BEPL2': 'BDM OTHER',
        'BES OTHER': 'ILOP',
        'BEUT2': 'BDM OTHER',
        'BRPA': 'BDM OTHER',
        'BUDA2': 'BDS OTHER',
        'BUSP': 'BES OTHER',
        'CA1': 'BDL OTHER',
        'CABE': 'BDM OTHER',
        'CACA': 'BDM OTHER',
        'CACO': 'BDL OTHER',
        'CADE': 'BDL OTHER',
        'CAGL': 'BDL OTHER',
        'CAIL': 'BDL OTHER',
        'CAJA9': 'BES OTHER',
        'CAMO': 'BDM OTHER',
        'CAOV': 'BDL OTHER',
        'CASP': 'BDM OTHER',
        'CATO': 'BDL OTHER',
        'CE2': 'BDL OTHER',
        'CEAT': 'CEM OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEJA': 'BDL OTHER',
        'CELA': 'CEL OTHER',
        'CEL OTHER': 'PIEC',
        'CEM OTHER': 'JUVI',
        'CEOC': 'BDL OTHER',
        'CES OTHER': 'PICO5',
        'CHLA2': 'CEL OTHER',
        'CHPI': 'CES OTHER',
        'CHRE': 'BDS OTHER',
        'CHTH': 'CEM OTHER',
        'CHVI': 'BDS OTHER',
        'CLLU': 'BDM OTHER',
        'CLTR': 'BDS OTHER',
        'CO1': 'COFL',
        'COAL': 'BDS OTHER',
        'COCO1': 'BDS OTHER',
        'COFL': 'COFL',
        'COKO': 'BDS OTHER',
        'COMA': 'BDS OTHER',
        'CR': 'BDS OTHER',
        'CRJA': 'CEL OTHER',
        'CRPH': 'BDS OTHER',
        'CRVI': 'BDS OTHER',
        'CULA': 'CEL OTHER',
        'CULE': 'CEL OTHER',
        'DIVI': 'BDM OTHER',
        'ELUM': 'BES OTHER',
        'EU1': 'BEL OTHER',
        'FAGR': 'BDL OTHER',
        'FASY': 'BDL OTHER',
        'FICA': 'BDS OTHER',
        'FISI': 'BDM OTHER',
        'FORS': 'BDS OTHER',
        'FRAM': 'BDL OTHER',
        'FRNI': 'BDM OTHER',
        'FRPE': 'BDL OTHER',
        'FRQU': 'BDL OTHER',
        'GIBI': 'BDM OTHER',
        'GLTR': 'BDL OTHER',
        'GYDI': 'BDL OTHER',
        'HA4': 'BES OTHER',
        'HACA': 'BDM OTHER',
        'HAVI': 'BDS OTHER',
        'HISY': 'BDS OTHER',
        'ILAQ': 'BES OTHER',
        'ILCA': 'BES OTHER',
        'ILCO2': 'BES OTHER',
        'ILOP': 'ILOP',
        'ILSP': 'BES OTHER',
        'JU': 'CEM OTHER',
        'JUNI': 'BDL OTHER',
        'JURE': 'BDM OTHER',
        'JUVI': 'JUVI',
        'KOPA': 'BDS OTHER',
        'LA6': 'LA6',
        'LADE': 'BDL OTHER',
        'LISP': 'ILOP',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'MA1': 'BDM OTHER',
        'MA2': 'MA2',
        'MAAC': 'BDL OTHER',
        'MABE': 'BES OTHER',
        'MAGR': 'MAGR',
        'MAPO': 'BDM OTHER',
        'MASO': 'BDS OTHER',
        'MAST': 'BDS OTHER',
        'MASY2': 'BDS OTHER',
        'MATS': 'BDS OTHER',
        'MAVI': 'BEM OTHER',
        'MEAZ': 'BDM OTHER',
        'MEGL': 'BDL OTHER',
        'MO': 'BDM OTHER',
        'MORU': 'BDL OTHER',
        'MYCE2': 'BES OTHER',
        'NYSY': 'BDM OTHER',
        'OSVI': 'BDM OTHER',
        'PATO': 'BDM OTHER',
        'PEL OTHER': 'PHDA4',
        'PEM OTHER': 'WARO',
        'PES OTHER': 'WAFI',
        'PHAM': 'BDM OTHER',
        'PHDA4': 'PHDA4',
        'PHFR': 'BES OTHER',
        'PHSP2': 'BES OTHER',
        'PI1': 'CEM OTHER',
        'PI2': 'CEL OTHER',
        'PIAB': 'CEL OTHER',
        'PICH': 'BDM OTHER',
        'PICO5': 'PICO5',
        'PICO6': 'CEL OTHER',
        'PIEC': 'PIEC',
        'PIGL1': 'CEM OTHER',
        'PIMU': 'CES OTHER',
        'PINI': 'CEM OTHER',
        'PIPA': 'CEL OTHER',
        'PIPU': 'CEM OTHER',
        'PIRE': 'CEL OTHER',
        'PIST': 'CEL OTHER',
        'PISY': 'CEM OTHER',
        'PITA': 'PITA',
        'PIVI': 'CEM OTHER',
        'PLAC': 'BDL OTHER',
        'PLOC': 'BDL OTHER',
        'POAL': 'BDL OTHER',
        'POBA': 'BDL OTHER',
        'PODE': 'BDL OTHER',
        'PONI': 'BDM OTHER',
        'PR': 'PR',
        'PRCA': 'BES OTHER',
        'PRCA2': 'BDS OTHER',
        'PRCE': 'BDS OTHER',
        'PRPA': 'BDM OTHER',
        'PRPE2': 'BDS OTHER',
        'PRSE1': 'BDL OTHER',
        'PRSE2': 'BDS OTHER',
        'PRSU': 'BDS OTHER',
        'PRTO': 'BDS OTHER',
        'PRYE': 'PRYE',
        'PSME': 'CEL OTHER',
        'PY': 'PYCA',
        'PYCA': 'PYCA',
        'PYCO': 'BDM OTHER',
        'PYKO': 'BES OTHER',
        'PYSP': 'BES OTHER',
        'QUAC': 'BDM OTHER',
        'QUAL': 'QUAL',
        'QUBI': 'BDL OTHER',
        'QUCO': 'BDL OTHER',
        'QUEL': 'BDL OTHER',
        'QUFA': 'BDL OTHER',
        'QUHE': 'BEM OTHER',
        'QUIM': 'BDL OTHER',
        'QULY': 'BDM OTHER',
        'QUMA1': 'BDL OTHER',
        'QUMA2': 'BDM OTHER',
        'QUMI': 'BDL OTHER',
        'QUMU': 'BDM OTHER',
        'QUNI': 'QUNI',
        'QUPA': 'BDL OTHER',
        'QUPH': 'QUPH',
        'QURO': 'BDL OTHER',
        'QURU': 'QURU',
        'QUSH': 'BDL OTHER',
        'QUST': 'BDL OTHER',
        'QUVE': 'BDL OTHER',
        'QUVI': 'BEL OTHER',
        'RHSP': 'BDS OTHER',
        'RHSP2': 'BDS OTHER',
        'ROBA': 'BDS OTHER',
        'ROPS': 'BDM OTHER',
        'SA': 'BDM OTHER',
        'SAAL': 'BDM OTHER',
        'SAGR': 'BDS OTHER',
        'SAMA': 'BDM OTHER',
        'SANI': 'BDM OTHER',
        'SAPA': 'WARO',
        'SAPE12': 'BDM OTHER',
        'SERE2': 'PES OTHER',
        'SOAU': 'BDS OTHER',
        'SOJA': 'BDM OTHER',
        'STJA': 'BDS OTHER',
        'SYRE': 'BDS OTHER',
        'SYSP': 'BDS OTHER',
        'TADI': 'BDL OTHER',
        'THOC': 'CEM OTHER',
        'THPL': 'CEL OTHER',
        'TIAM': 'BDL OTHER',
        'TICO': 'BDM OTHER',
        'TOTA': 'CES OTHER',
        'TRSE6': 'BDS OTHER',
        'TSCA': 'CEM OTHER',
        'ULAL': 'ULAL',
        'ULAM': 'BDL OTHER',
        'ULPA': 'BDM OTHER',
        'ULPU': 'BDL OTHER',
        'ULRU': 'BDM OTHER',
        'ULS': 'BDL OTHER',
        'VIAG': 'BDS OTHER',
        'VIPR': 'BDS OTHER',
        'VISP2': 'BDS OTHER',
        'WAFI': 'WAFI',
        'WARO': 'WARO',
        'YU1': 'PES OTHER',
        'ZESE': 'BDL OTHER',
    } # END PiedmtCLT
    ,
##################################################
    'SoCalCSMA': {
        'AC': 'BDL OTHER',
        'ACBA2': 'BEM OTHER',
        'ACBU': 'BDS OTHER',
        'ACDE': 'BEM OTHER',
        'ACLO': 'BEM OTHER',
        'ACME': 'BEL OTHER',
        'ACNE': 'BDL OTHER',
        'ACOB': 'BDS OTHER',
        'ACPA': 'BDL OTHER',
        'ACPE1': 'BDL OTHER',
        'ACRU': 'BDL OTHER',
        'ACSA1': 'BDL OTHER',
        'AGFL': 'BES OTHER',
        'ALCO2': 'BDM OTHER',
        'ALEX': 'BES OTHER',
        'ALJU': 'BDS OTHER',
        'ALRH': 'BDM OTHER',
        'ANCH4': 'BES OTHER',
        'ARBI': 'CEL OTHER',
        'ARCO24': 'CEL OTHER',
        'ARCU': 'PES OTHER',
        'ARHE': 'CEL OTHER',
        'ARRO': 'WARO',
        'ARUN': 'BES OTHER',
        'BABL': 'BES OTHER',
        'BAPU': 'BES OTHER',
        'BAVA': 'BDS OTHER',
        'BDL OTHER': 'PLAC',
        'BDM OTHER': 'LIST',
        'BDS OTHER': 'JAMI',
        'BE': 'BDM OTHER',
        'BEL OTHER': 'EUFI81',
        'BEM OTHER': 'CICA',
        'BENI': 'BDM OTHER',
        'BEPE': 'BDM OTHER',
        'BERE': 'PES OTHER',
        'BES OTHER': 'POMA',
        'BIJA': 'BEL OTHER',
        'BR': 'PES OTHER',
        'BR1': 'BDM OTHER',
        'BRAC': 'BES OTHER',
        'BRAC2': 'BDM OTHER',
        'BRAR': 'PES OTHER',
        'BRED': 'PES OTHER',
        'BRPO': 'BEM OTHER',
        'BRPA': 'BDM OTHER',
        'BRPO': 'CICA',
        'BUCA': 'PES OTHER',
        'CA4': 'BDL OTHER',
        'CA52': 'CEL OTHER',
        'CACA3': 'BEM OTHER',
        'CACI': 'CACI',
        'CACU8': 'CEDE',
        'CADE2': 'CEL OTHER',
        'CAED': 'BEL OTHER',
        'CAEX': 'BES OTHER',
        'CALE': 'BES OTHER',
        'CASA5': 'BES OTHER',
        'CASP11': 'BES OTHER',
        'CAST': 'CEL OTHER',
        'CATW': 'BES OTHER',
        'CAVI': 'BES OTHER',
        'CE2': 'BDL OTHER',
        'CEAT': 'CEDE',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEDE',
        'CEFI2': 'BDM OTHER',
        'CEL OTHER': 'CEDE',
        'CEM OTHER': 'PIBR2',
        'CEOC2': 'BDS OTHER',
        'CESI3': 'CESI3',
        'CES OTHER': 'PICO5',
        'CH': 'CEL OTHER',
        'CHHU': 'PES OTHER',
        'CHSP': 'BEM OTHER',
        'CICA': 'CICA',
        'CILI': 'BES OTHER',
        'CISI': 'BES OTHER',
        'COAU': 'PES OTHER',
        'COLA': 'BES OTHER',
        'COLA18': 'BES OTHER',
        'CRJA': 'CEL OTHER',
        'CRPA': 'BDS OTHER',
        'CRRU': 'BES OTHER',
        'CU': 'CEL OTHER',
        'CUAN': 'CUAN',
        'CULE': 'CES OTHER',
        'CUMA': 'CEL OTHER',
        'CUSE': 'CEL OTHER',
        'CYRE11': 'CES OTHER',
        'DIVI': 'BDS OTHER',
        'DOVI': 'BES OTHER',
        'DRDR': 'PES OTHER',
        'DUER': 'BES OTHER',
        'ERBI': 'BEL OTHER',
        'ERCA': 'BEL OTHER',
        'ERCO': 'BEL OTHER',
        'ERDE': 'BES OTHER',
        'ERFA': 'BEM OTHER',
        'ERHU4': 'BDS OTHER',
        'ERJA': 'BES OTHER',
        'ERLY': 'BEL OTHER',
        'EU1': 'BEL OTHER',
        'EUCA': 'BEL OTHER',
        'EUCA1': 'BEL OTHER',
        'EUCI': 'BEM OTHER',
        'EUCI2': 'BEL OTHER',
        'EUCL': 'BEL OTHER',
        'EUCO24': 'BES OTHER',
        'EUCO3': 'BEL OTHER',
        'EUER': 'BEM OTHER',
        'EUFI81': 'EUFI81',
        'EUGL': 'BEL OTHER',
        'EUGR': 'BEL OTHER',
        'EULE': 'BEM OTHER',
        'EULE2': 'BES OTHER',
        'EUMA23': 'BEL OTHER',
        'EUNI': 'BEM OTHER',
        'EUOC9': 'BEL OTHER',
        'EUPO': 'BEL OTHER',
        'EURU': 'BEL OTHER',
        'EUSI': 'BEL OTHER',
        'EUSM': 'BES OTHER',
        'EUTO11': 'BEM OTHER',
        'EUVI': 'BEL OTHER',
        'FESE': 'BES OTHER',
        'FI1': 'BEM OTHER',
        'FIAL5': 'BES OTHER',
        'FIBE': 'BEM OTHER',
        'FICA': 'BDS OTHER',
        'FIEL': 'BEM OTHER',
        'FILY': 'BES OTHER',
        'FIMA2': 'BEL OTHER',
        'FIMI': 'FIMI',
        'FIRE4': 'BEM OTHER',
        'FIRU': 'BEM OTHER',
        'FISI': 'BDM OTHER',
        'FIWA': 'BEL OTHER',
        'FRMA6': 'BDM OTHER',
        'FRUH': 'BEL OTHER',
        'FRVE': 'BEL OTHER',
        'GEPA': 'BES OTHER',
        'GIBI': 'BDM OTHER',
        'GRRO': 'BEL OTHER',
        'HACA3': 'BES OTHER',
        'HALA': 'BES OTHER',
        'HASU': 'CES OTHER',
        'HEAR': 'BES OTHER',
        'HIRO-SI': 'BES OTHER',
        'HOFO': 'PEM OTHER',
        'HYFL': 'BES OTHER',
        'ILAL': 'BES OTHER',
        'JAMI': 'JAMI',
        'JUCH': 'CES OTHER',
        'JUHI': 'BDL OTHER',
        'JURE': 'BDM OTHER',
        'KOBI': 'BDM OTHER',
        'KOPA': 'BDM OTHER',
        'LAIN': 'BDS OTHER',
        'LAPA': 'BEM OTHER',
        'LE14': 'BES OTHER',
        'LELA12': 'BES OTHER',
        'LIAU9': 'BDM OTHER',
        'LILU': 'BEM OTHER',
        'LIOR': 'BDM OTHER',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'MABO': 'BEM OTHER',
        'MAFL80': 'BDS OTHER',
        'MAGR': 'MAGR',
        'MAIN8': 'BES OTHER',
        'MALU4': 'BDS OTHER',
        'MAPU': 'BDS OTHER',
        'MASO': 'BDS OTHER',
        'MASY2': 'BDS OTHER',
        'MATE': 'BES OTHER',
        'MATI': 'BDS OTHER',
        'MEAR': 'BES OTHER',
        'MEBR9': 'BES OTHER',
        'MEEX': 'MEEX',
        'MENE': 'BES OTHER',
        'MEQU': 'MEQU',
        'MEST': 'BEM OTHER',
        'MOAL': 'BDL OTHER',
        'MU5': 'BES OTHER',
        'MYCO': 'BES OTHER',
        'MYLA': 'BES OTHER',
        'NEOL': 'CACI',
        'OLEU': 'BES OTHER',
        'PALO8': 'BDS OTHER',
        'PEAM': 'BDS OTHER',
        'PEBO': 'BDS OTHER',
        'PEIN17': 'BES OTHER',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PHFR': 'BES OTHER',
        'PHRE': 'PEM OTHER',
        'PHRO': 'PEM OTHER',
        'PI1': 'CEL OTHER',
        'PIBR2': 'PIBR2',
        'PICA': 'PICA',
        'PICH': 'BDM OTHER',
        'PICO5': 'PICO5',
        'PICR': 'BEM OTHER',
        'PIDE': 'CEL OTHER',
        'PIED': 'CES OTHER',
        'PIHA': 'CEL OTHER',
        'PIPI2': 'CEL OTHER',
        'PIPI6': 'CEL OTHER',
        'PIRA': 'CEL OTHER',
        'PIRH': 'BEM OTHER',
        'PIRO': 'BES OTHER',
        'PITH': 'CES OTHER',
        'PITO': 'BEM OTHER',
        'PITO2': 'CEL OTHER',
        'PIUN': 'PIUN',
        'PIVI5': 'BEM OTHER',
        'PLAC': 'PLAC',
        'PLRA': 'BDL OTHER',
        'POAL': 'BDL OTHER',
        'POGR2': 'POMA',
        'POHE2': 'BES OTHER',
        'POMA': 'POMA',
        'PONI': 'BDL OTHER',
        'PR': 'BDS OTHER',
        'PRAM2': 'BDS OTHER',
        'PRAR': 'BDS OTHER',
        'PRCA': 'BES OTHER',
        'PRCA2': 'BDS OTHER',
        'PRCE': 'BDS OTHER',
        'PRDO': 'BDS OTHER',
        'PRDU': 'BDS OTHER',
        'PRLY': 'BDS OTHER',
        'PRPE2': 'BDS OTHER',
        'PRSE2': 'BDS OTHER',
        'PSCA': 'BES OTHER',
        'PSME': 'CEL OTHER',
        'PYCA': 'BES OTHER',
        'PYCO': 'BES OTHER',
        'PYKA': 'BES OTHER',
        'QUAG': 'BEL OTHER',
        'QUIL2': 'BEL OTHER',
        'QURU': 'BDL OTHER',
        'QUSA2': 'BES OTHER',
        'QUSU': 'BEL OTHER',
        'QUVI': 'BEL OTHER',
        'RARI': 'PES OTHER',
        'RASA5': 'BEL OTHER',
        'RHBA7': 'PES OTHER',
        'RHLA': 'BES OTHER',
        'ROPS': 'BDL OTHER',
        'SAMA': 'BDL OTHER',
        'SAPE12': 'BDL OTHER',
        'SASA': 'BES OTHER',
        'SCMO': 'BEM OTHER',
        'SCPO': 'BES OTHER',
        'SCTE': 'SCTE',
        'SESE': 'CEL OTHER',
        'SO1': 'BES OTHER',
        'SPCA': 'BEL OTHER',
        'STNI': 'BES OTHER',
        'STSI': 'BES OTHER',
        'SYPA2': 'BEM OTHER',
        'TACH3': 'BDM OTHER',
        'TAMU': 'BDL OTHER',
        'THOR': 'CES OTHER',
        'THPE3': 'BES OTHER',
        'TRCO': 'TRCO',
        'TRFO': 'PES OTHER',
        'TRLA': 'BES OTHER',
        'TUCA': 'BES OTHER',
        'ULAM': 'BDL OTHER',
        'ULPA': 'BEL OTHER',
        'ULPU': 'BEL OTHER',
        'UMCA': 'BEL OTHER',
        'VILU6': 'BEL OTHER',
        'VITI2': 'BES OTHER',
        'WAFI': 'WARO',
        'WARO': 'WARO',
        'XYCO': 'PES OTHER',
        'YU1': 'PES OTHER',
        'YUGL2': 'PES OTHER',
        'YUGU': 'PES OTHER',
    } # END SoCalCSMA
    ,
##################################################
    'SWDsrtGDL': {
        'ACAN': 'ACSA3',
        'ACFA': 'ACFA',
        'ACMI': 'ACSA3',
        'ACSA': 'ACSA3',
        'ACSA3': 'ACSA3',
        'ACSP2': 'ACSA3',
        'ACST': 'BES OTHER',
        'ALJU': 'BDM OTHER',
        'ARRO': 'PES OTHER',
        'BAVA': 'BDS OTHER',
        'BDL OTHER': 'FRUH',
        'BDM OTHER': 'PRCH',
        'BDS OTHER': 'ACFA',
        'BEL OTHER': 'EUMI2',
        'BEM OTHER': 'BRPO',
        'BES OTHER': 'RHLA',
        'BRAR': 'PES OTHER',
        'BRPO': 'BRPO',
        'CAEQ': 'CEL OTHER',
        'CAIL': 'BDL OTHER',
        'CAVI': 'BES OTHER',
        'CEFL': 'CEFL',
        'CEL OTHER': 'PIHA',
        'CEMI': 'CEFL',
        'CEM OTHER': 'PIBR2',
        'CEPR': 'CEFL',
        'CESI3': 'BEM OTHER',
        'CES OTHER': 'PICO5',
        'CHHU': 'BES OTHER',
        'CHLI': 'CHLI',
        'CISP': 'BES OTHER',
        'CUGU': 'CEL OTHER',
        'CUSE': 'CEL OTHER',
        'CYOB': 'BDS OTHER',
        'DASI': 'BEM OTHER',
        'EBEB': 'BES OTHER',
        'EU1': 'EUMI2',
        'EUCA1': 'EUMI2',
        'EULE': 'EUMI2',
        'EUMI2': 'EUMI2',
        'EUPO': 'BEL OTHER',
        'EURU': 'EUMI2',
        'EUSI': 'EUMI2',
        'EUSP': 'EUMI2',
        'EUTO11': 'EUMI2',
        'FIBE': 'BES OTHER',
        'FICA': 'BDS OTHER',
        'FIRE4': 'BEM OTHER',
        'FRUH': 'FRUH',
        'FRVE': 'FRVE',
        'GEPA': 'BES OTHER',
        'GLTR': 'BDL OTHER',
        'GRRO': 'BEL OTHER',
        'JAMI': 'BDM OTHER',
        'JU': 'CES OTHER',
        'LAIN': 'BDS OTHER',
        'LILU': 'BES OTHER',
        'LYMI': 'PRCH',
        'MA2': 'BDS OTHER',
        'MAGR': 'BEM OTHER',
        'MATI': 'BDM OTHER',
        'MEAZ': 'BDM OTHER',
        'MOAL': 'MOAL',
        'MYCO': 'BES OTHER',
        'NEOL': 'BES OTHER',
        'OLEU': 'OLEU',
        'OLTE': 'BES OTHER',
        'OTHER': 'BES OTHER',
        'PAAC': 'PAAC',
        'PEL OTHER': 'PHCA',
        'PEM OTHER': 'PHDA4',
        'PES OTHER': 'WARO',
        'PHCA': 'PHCA',
        'PHDA4': 'PHDA4',
        'PI2': 'CEL OTHER',
        'PIBR2': 'PIBR2',
        'PICA': 'CEL OTHER',
        'PICH': 'PICH',
        'PICO5': 'PICO5',
        'PIEL2': 'PIEL2',
        'PIHA': 'PIHA',
        'PIRO': 'CEL OTHER',
        'PLRA': 'BDL OTHER',
        'PLWR': 'BDL OTHER',
        'PO': 'BDL OTHER',
        'POBAB2': 'BDL OTHER',
        'POFR': 'BDL OTHER',
        'PR': 'BDS OTHER',
        'PR6': 'PRCH',
        'PRAL2': 'BEM OTHER',
        'PRAR': 'BDS OTHER',
        'PRCE': 'BDS OTHER',
        'PRCH': 'PRCH',
        'PRDU': 'BDS OTHER',
        'PRGL2': 'PRCH',
        'PRPE2': 'BDS OTHER',
        'PRPU2': 'PRCH',
        'PRVE': 'PRCH',
        'PYCO': 'BDM OTHER',
        'PYKA': 'BES OTHER',
        'QUMU': 'BDL OTHER',
        'QUSU': 'BEL OTHER',
        'QUVI': 'QUVI',
        'RHLA': 'RHLA',
        'SA': 'BDS OTHER',
        'SABA': 'BDM OTHER',
        'SCMO': 'BEM OTHER',
        'SOSE': 'BES OTHER',
        'TACH2': 'BDS OTHER',
        'TAMU': 'CEL OTHER',
        'THOR': 'BES OTHER',
        'THPE3': 'BES OTHER',
        'ULPA': 'ULPA',
        'VIAG': 'BDS OTHER',
        'WAFI': 'WAFI',
        'WARO': 'WARO'
    } # END SWDsrtGDL
    ,
##################################################
    'TpIntWBOI': {
        'AB': 'CEL OTHER',
        'ABAL': 'CEL OTHER',
        'ABCO': 'CEL OTHER',
        'ABHO': 'CEL OTHER',
        'ABHO2': 'CEL OTHER',
        'AC': 'ACSA1',
        'ACCA': 'ACPL',
        'ACGI': 'ACPL',
        'ACGR': 'ACPL',
        'ACGR3': 'ACPL',
        'ACNE': 'ACSA1',
        'ACNI': 'ACSA1',
        'ACPL': 'ACPL',
        'ACPS': 'ACPL',
        'ACRU': 'ACPL',
        'ACSA1': 'ACSA1',
        'ACSA2': 'ACSA2',
        'ACTR': 'ACPL',
        'AEGL': 'BDM OTHER',
        'AEHI': 'BDM OTHER',
        'AIAL': 'BDL OTHER',
        'ALCO2': 'BDM OTHER',
        'ALGL': 'BDM OTHER',
        'ALJU': 'BDS OTHER',
        'AMAR': 'BDS OTHER',
        'BDL OTHER': 'FRPE',
        'BDM OTHER': 'ACPL',
        'BDS OTHER': 'MA2',
        'BE': 'BDM OTHER',
        'BENI': 'BDL OTHER',
        'BEPA': 'BDL OTHER',
        'BEPE': 'BDM OTHER',
        'BES OTHER': 'ILOP',
        'CA1': 'BDL OTHER',
        'CABE': 'BDM OTHER',
        'CABI': 'BDL OTHER',
        'CACA': 'BDS OTHER',
        'CADE': 'BDL OTHER',
        'CASP': 'CASP',
        'CE7': 'CEM OTHER',
        'CEAT': 'CEM OTHER',
        'CECA': 'BDS OTHER',
        'CEDE': 'CEL OTHER',
        'CEJA': 'BDM OTHER',
        'CEL OTHER': 'PIPU',
        'CEM OTHER': 'PISY',
        'CEOC': 'BDM OTHER',
        'CES OTHER': 'PIED',
        'CLLU': 'BDS OTHER',
        'CO1': 'BDS OTHER',
        'CO2': 'BDM OTHER',
        'COCO1': 'BDS OTHER',
        'COCO2': 'BDM OTHER',
        'COFL': 'BDS OTHER',
        'COOB': 'BDS OTHER',
        'CR': 'CR',
        'CRLA80': 'CR',
        'CROX': 'CR',
        'CRPH': 'CR',
        'CRVI': 'CR',
        'CU': 'CEM OTHER',
        'DIVI': 'BDS OTHER',
        'ELAN': 'BDS OTHER',
        'EUUL': 'BDM OTHER',
        'FA': 'BDM OTHER',
        'FASY': 'BDM OTHER',
        'FR': 'FRPE',
        'FRAM': 'FRAM',
        'FREX': 'FRPE',
        'FRMA': 'FRPE',
        'FRNI': 'FRPE',
        'FROR': 'FRPE',
        'FROX': 'FRPE',
        'FRPE': 'FRPE',
        'FRQU': 'FRPE',
        'GIBI': 'BDM OTHER',
        'GLCA': 'GLTR',
        'GLTR': 'GLTR',
        'GYDI': 'BDL OTHER',
        'ILOP': 'ILOP',
        'JU': 'CEM OTHER',
        'JUNI': 'JUNI',
        'JURE': 'JUNI',
        'JUSC': 'CES OTHER',
        'JUVI': 'CEM OTHER',
        'KOPA': 'BDS OTHER',
        'LADE': 'BDL OTHER',
        'LAWA': 'BDS OTHER',
        'LIST': 'LIST',
        'LITU': 'BDL OTHER',
        'MA1': 'BDS OTHER',
        'MA2': 'MA2',
        'MAAC': 'BDL OTHER',
        'MAAM': 'BDS OTHER',
        'MAPU': 'MA2',
        'MOAL': 'BDM OTHER',
        'MORU': 'BDM OTHER',
        'PHAM': 'BDM OTHER',
        'PI1': 'PIPU',
        'PI2': 'CEL OTHER',
        'PIAB': 'CEL OTHER',
        'PIAS': 'PIPU',
        'PIAT': 'CEM OTHER',
        'PICE2': 'CEM OTHER',
        'PICO2': 'CEM OTHER',
        'PIED': 'PIED',
        'PIEN': 'CEL OTHER',
        'PIGL1': 'PIPU',
        'PIGL2': 'CEM OTHER',
        'PIMA': 'CEL OTHER',
        'PIMO3': 'CEM OTHER',
        'PIMU': 'CES OTHER',
        'PINI': 'CEM OTHER',
        'PIOM': 'PIPU',
        'PIOR': 'PIPU',
        'PIPO': 'CEL OTHER',
        'PIPU': 'PIPU',
        'PISE': 'CEL OTHER',
        'PIST': 'CEL OTHER',
        'PISY': 'PISY',
        'PIWA3': 'CEM OTHER',
        'PLAC': 'PLAC',
        'PLOC': 'PLOC',
        'PO': 'BDL OTHER',
        'POAL': 'BDL OTHER',
        'POBA': 'BDL OTHER',
        'POCA2': 'BDL OTHER',
        'PODE': 'BDL OTHER',
        'POGR': 'BDS OTHER',
        'PONI': 'BDL OTHER',
        'POTR1': 'BDM OTHER',
        'POTR2': 'BDL OTHER',
        'PR': 'MA2',
        'PRAR': 'MA2',
        'PRBL': 'MA2',
        'PRCE': 'MA2',
        'PRPE2': 'MA2',
        'PRSA': 'MA2',
        'PRSE2': 'MA2',
        'PRTR': 'MA2',
        'PRVI': 'MA2',
        'PSME': 'CEL OTHER',
        'PTCO': 'BDS OTHER',
        'PTTR': 'BDS OTHER',
        'PYCA': 'PYCA',
        'PYCO': 'PYCA',
        'PYFA': 'PYCA',
        'PYIO': 'MA2',
        'QU': 'QURU',
        'QUAC': 'QURU',
        'QUAL': 'QURU',
        'QUAL3': 'QURU',
        'QUBI': 'QURU',
        'QUCO': 'QURU',
        'QUFA': 'QURU',
        'QUKE': 'QURU',
        'QULA2': 'QURU',
        'QUMA1': 'QURU',
        'QUMU': 'QURU',
        'QUPA': 'QURU',
        'QUPH': 'QURU',
        'QURO': 'QURU',
        'QURU': 'QURU',
        'QUSE': 'QURU',
        'QUVE': 'QURU',
        'QUVI': 'QURU',
        'RHSP': 'BDS OTHER',
        'RHTY': 'BDS OTHER',
        'ROPS': 'ROPS',
        'SA': 'BDM OTHER',
        'SAMA': 'BDS OTHER',
        'SANI': 'BDM OTHER',
        'SCVE': 'CEM OTHER',
        'SEGI': 'CEL OTHER',
        'SOAM': 'BDS OTHER',
        'SOAU': 'BDS OTHER',
        'SOJA': 'BDM OTHER',
        'SYRE': 'BDS OTHER',
        'TADI': 'BDL OTHER',
        'THOC': 'CEL OTHER',
        'THPL': 'CEL OTHER',
        'TI': 'TIAM',
        'TIAM': 'TIAM',
        'TICO': 'TIAM',
        'TITO': 'TIAM',
        'TSCA': 'CEL OTHER',
        'ULAM': 'ULPU',
        'ULGL': 'ULPU',
        'ULPA': 'ULPU',
        'ULPR': 'ULPU',
        'ULPU': 'ULPU',
        'ULS': 'ULPU'
    } # END TpIntWBOI
    ,
##################################################
    'TropicPacXXX': {
        'ACCO': 'BEM OTHER',
        'ACKO': 'BEL OTHER',
        'ACWR': 'PES OTHER',
        'AGVI14': 'CEL OTHER',
        'ALFA': 'BEL OTHER',
        'ALJU': 'BDM OTHER',
        'ALLE': 'BDL OTHER',
        'ALMO': 'BEL OTHER',
        'AMNO4': 'BEM OTHER',
        'ANIM': 'BEL OTHER',
        'ANMU': 'BES OTHER',
        'ANRE': 'BDM OTHER',
        'ANSQ': 'BDS OTHER',
        'ARAL': 'PES OTHER',
        'ARAL2': 'BEL OTHER',
        'ARCO24': 'CEL OTHER',
        'ARCU': 'PES OTHER',
        'ARHE': 'CEL OTHER',
        'ARHE2': 'BEL OTHER',
        'AVBI': 'BEL OTHER',
        'AVCA': 'BES OTHER',
        'AZIN2': 'BEL OTHER',
        'BA13': 'BEM OTHER',
        'BABL': 'BABL',
        'BAHO3': 'BES OTHER',
        'BAPU': 'BEM OTHER',
        'BAVA': 'BEM OTHER',
        'BDL OTHER': 'PISA2',
        'BDM OTHER': 'CANE33',
        'BDS OTHER': 'DERE',
        'BEL OTHER': 'FIBE',
        'BEM OTHER': 'CISP2',
        'BERE': 'BEM OTHER',
        'BES OTHER': 'BABL',
        'BIOR': 'BEM OTHER',
        'BO9': 'BES OTHER',
        'BOSP8': 'BES OTHER',
        'BRAC': 'BEL OTHER',
        'BUBU': 'BEL OTHER',
        'BUCA': 'PEM OTHER',
        'CACA73': 'BDL OTHER',
        'CACI': 'BES OTHER',
        'CAEQ': 'CAEQ',
        'CAFI': 'CANE33',
        'CAGR11': 'BDL OTHER',
        'CAIN4': 'CAIN4',
        'CALO': 'BEL OTHER',
        'CAMA37': 'BES OTHER',
        'CAMI36': 'PES OTHER',
        'CANE33': 'CANE33',
        'CAPA3': 'BES OTHER',
        'CARI9': 'BES OTHER',
        'CARO': 'CANE33',
        'CAVI': 'BEM OTHER',
        'CEL OTHER': 'PIRA',
        'CEM OTHER': 'PIBR2',
        'CESI3': 'BEL OTHER',
        'CES OTHER': 'PICO5',
        'CHHU': 'PES OTHER',
        'CHLU': 'PES OTHER',
        'CHOL': 'BEM OTHER',
        'CHSP': 'BDL OTHER',
        'CICA': 'BEL OTHER',
        'CIGR': 'BES OTHER',
        'CILI': 'BES OTHER',
        'CIPA': 'BEL OTHER',
        'CIRE3': 'BES OTHER',
        'CISI': 'BEM OTHER',
        'CISP': 'BES OTHER',
        'CISP2': 'CISP2',
        'CIVE2': 'BEM OTHER',
        'CLRO': 'BES OTHER',
        'COCO1': 'BDS OTHER',
        'COERA2': 'COERA2',
        'CONU': 'CONU',
        'CORA13': 'BEM OTHER',
        'COSE2': 'COSU2',
        'COSU2': 'COSU2',
        'COUT': 'PEL OTHER',
        'COUV': 'BES OTHER',
        'COVI': 'BDL OTHER',
        'CRCU': 'BES OTHER',
        'CU': 'CEL OTHER',
        'CUAN': 'BEM OTHER',
        'CUSE': 'CEL OTHER',
        'CYRE11': 'PES OTHER',
        'DA2': 'BDL OTHER',
        'DERE': 'DERE',
        'DR': 'BES OTHER',
        'DYDE2': 'PES OTHER',
        'ELOR2': 'ELOR2',
        'ENCY': 'BDL OTHER',
        'ER15': 'BDL OTHER',
        'ERCR': 'BEM OTHER',
        'ERJA': 'BES OTHER',
        'ERSA11': 'BDL OTHER',
        'ERVA7': 'BDL OTHER',
        'ERVAO': 'BDL OTHER',
        'EU1': 'BEL OTHER',
        'EUCI2': 'BEL OTHER',
        'EUDE': 'BEL OTHER',
        'EURO': 'BEL OTHER',
        'EUTI': 'BDS OTHER',
        'EUUN2': 'BEM OTHER',
        'FABE': 'BEL OTHER',
        'FI1': 'FIBE',
        'FIBE': 'FIBE',
        'FIBE2': 'FIBE',
        'FICA': 'FIBE',
        'FIDE6': 'FIDE6',
        'FIEL': 'FIBE',
        'FILY': 'FIBE',
        'FIMA2': 'FIBE',
        'FIMI2': 'FIBE',
        'FIRE3': 'FIBE',
        'FIVI3': 'FIBE',
        'FRUH': 'BDL OTHER',
        'GA2': 'BES OTHER',
        'GRRO': 'BEL OTHER',
        'GUOF': 'BES OTHER',
        'HACA3': 'BEM OTHER',
        'HAPE7': 'BES OTHER',
        'HELI9': 'BEL OTHER',
        'HENY': 'BEL OTHER',
        'HISP': 'BES OTHER',
        'HITI': 'BDM OTHER',
        'HUCR': 'BDL OTHER',
        'HYLA': 'PES OTHER',
        'HYVE9': 'PES OTHER',
        'ILPA2': 'ILPA2',
        'JAIN': 'BES OTHER',
        'JAMI': 'BDM OTHER',
        'JUCH': 'CEL OTHER',
        'JUCHS6': 'CEL OTHER',
        'KOEL': 'BDM OTHER',
        'LAIN': 'BDS OTHER',
        'LAPA': 'BEL OTHER',
        'LASP': 'LASP',
        'LELE': 'BES OTHER',
        'LICH': 'PES OTHER',
        'LICH4': 'BEL OTHER',
        'LIJA': 'BES OTHER',
        'MAGR': 'BES OTHER',
        'MAIN': 'BEL OTHER',
        'MAIN8': 'BEL OTHER',
        'MAZA': 'BEL OTHER',
        'MEAZ': 'BDL OTHER',
        'MEPO5': 'BEL OTHER',
        'MEQU': 'MEQU',
        'MICA21': 'BEM OTHER',
        'MO': 'BDS OTHER',
        'MOCI3': 'BES OTHER',
        'MONI': 'BDS OTHER',
        'MOOL': 'BEM OTHER',
        'MU5': 'BES OTHER',
        'MUPA4': 'BES OTHER',
        'NEOL': 'BES OTHER',
        'NOEM': 'BEL OTHER',
        'OCEL': 'BES OTHER',
        'OCSE2': 'BES OTHER',
        'OLEU': 'BEL OTHER',
        'ORCO9': 'PEL OTHER',
        'PACE8': 'BES OTHER',
        'PASP': 'PEM OTHER',
        'PATE2': 'BEM OTHER',
        'PEAM': 'BEL OTHER',
        'PEL OTHER': 'CONU',
        'PEM OTHER': 'PHDA4',
        'PEPT': 'BEL OTHER',
        'PES OTHER': 'VEME',
        'PH7': 'PEM OTHER',
        'PHCA': 'PEL OTHER',
        'PHDA4': 'PHDA4',
        'PHRO': 'PES OTHER',
        'PI2': 'CEL OTHER',
        'PI23': 'BEM OTHER',
        'PIAR9': 'BEM OTHER',
        'PIBR2': 'PIBR2',
        'PICO5': 'PICO5',
        'PIDI3': 'BEL OTHER',
        'PIDU': 'BEL OTHER',
        'PIPE8': 'BEM OTHER',
        'PIPI2': 'CEL OTHER',
        'PIRA': 'PIRA',
        'PIRA2': 'BEL OTHER',
        'PISA2': 'PISA2',
        'PITH': 'CEL OTHER',
        'PL13': 'BES OTHER',
        'PLOR80': 'CEL OTHER',
        'PLPI4': 'BDL OTHER',
        'PO3': 'CEL OTHER',
        'POLO21': 'BDL OTHER',
        'PONE21': 'CEL OTHER',
        'POUS2': 'CEL OTHER',
        'PRPA11': 'PES OTHER',
        'PRPA2': 'BEL OTHER',
        'PSCA': 'BES OTHER',
        'PSEL5': 'BDL OTHER',
        'PSGU': 'BEM OTHER',
        'PTIN': 'BDL OTHER',
        'PTMA8': 'PES OTHER',
        'RAMA': 'BEL OTHER',
        'RORE2': 'PEM OTHER',
        'SAMA': 'BEM OTHER',
        'SCMO': 'BEM OTHER',
        'SCPU18': 'BES OTHER',
        'SCTE': 'BDS OTHER',
        'SEGR5': 'BEL OTHER',
        'SESU4': 'BES OTHER',
        'SPCA': 'BEL OTHER',
        'SWMA': 'SWMA',
        'SYCO': 'PEM OTHER',
        'SYJA': 'BEM OTHER',
        'SYRO': 'PEL OTHER',
        'TAAR': 'TAAR',
        'TABA2': 'TACH',
        'TACH4': 'TACH',
        'TADO2': 'TACH',
        'TAIM': 'TAAR',
        'TAIN': 'BEL OTHER',
        'TAPA': 'TAPA',
        'TAPA13': 'BES OTHER',
        'TASP': 'TAAR',
        'TECA': 'BDL OTHER',
        'THPE3': 'BES OTHER',
        'THPU': 'BEM OTHER',
        'TITU': 'BDL OTHER',
        'TOAR2': 'BEM OTHER',
        'VEME': 'VEME',
        'VIPA6': 'BEL OTHER',
        'WARO': 'PES OTHER'
    } # END TropicPacXXX
}

# The currency conversions are in the following units:
# electricity: $/kWh
# natural_gas: $/kBTU
# h20: $/gal
# co2, o3, nox, pm10, sox, voc: $/lb
ITREE_REGIONS = {
    'CaNCCoJBK': {
        'name': 'Northern California Coast',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.1323,
            'natural_gas_kbtu_to_currency': 0.013048,
            'h20_gal_to_currency': 0.004,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 10.3101,
            'nox_lb_to_currency': 10.3101,
            'pm10_lb_to_currency': 11.7901,
            'sox_lb_to_currency': 3.67,
            'voc_lb_to_currency': 7.22
        }
    },
    'CenFlaXXX': {
        'name': 'Central Florida',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.13182,
            'natural_gas_kbtu_to_currency': 0.002678,
            'h20_gal_to_currency': 0.003,
            'co2_lb_to_currency': 0.0034,
            'o3_lb_to_currency': 2.2,
            'nox_lb_to_currency': 2.2,
            'pm10_lb_to_currency': 2.1,
            'sox_lb_to_currency': 2.01,
            'voc_lb_to_currency': 1.03
        }
    },
    'GulfCoCHS': {
        'name': 'Coastal Plain',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.09339,
            'natural_gas_kbtu_to_currency': 0.019742,
            'h20_gal_to_currency': 0.00605,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 1.04,
            'nox_lb_to_currency': 1.04,
            'pm10_lb_to_currency': 0.76,
            'sox_lb_to_currency': 1.28,
            'voc_lb_to_currency': 1.48
        }
    },
    'InlEmpCLM': {
        'name': 'Inland Empire',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.20148,
            'natural_gas_kbtu_to_currency': 0.0066871,
            'h20_gal_to_currency': 0.0055,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 3.84,
            'nox_lb_to_currency': 3.84,
            'pm10_lb_to_currency': 4.63,
            'sox_lb_to_currency': 2.43,
            'voc_lb_to_currency': 1.92
        }
    },
    'InlValMOD': {
        'name': 'Inland Valleys',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.1166,
            'natural_gas_kbtu_to_currency': 0.0125278,
            'h20_gal_to_currency': 0.0078,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 5.0032,
            'nox_lb_to_currency': 12.79,
            'pm10_lb_to_currency': 9.41,
            'sox_lb_to_currency': 3.72,
            'voc_lb_to_currency': 4.69
        }
    },
    'InterWABQ': {
        'name': 'Interior West',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.078844,
            'natural_gas_kbtu_to_currency': 0.011,
            'h20_gal_to_currency': 0.005,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 0.61,
            'nox_lb_to_currency': 0.61,
            'pm10_lb_to_currency': 1.14,
            'sox_lb_to_currency': 1.42,
            'voc_lb_to_currency': 0.19
        }
    },
    'LoMidWXXX': {
        'name': 'Lower Midwest',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.068,
            'natural_gas_kbtu_to_currency': 0.00973,
            'h20_gal_to_currency': 0.0062,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 0.82,
            'nox_lb_to_currency': 0.82,
            'pm10_lb_to_currency': 0.99,
            'sox_lb_to_currency': 1.50,
            'voc_lb_to_currency': 0.3
        }
    },
    'MidWstMSP': {
        'name': 'Midwest',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.0759,
            'natural_gas_kbtu_to_currency': 0.0098,
            'h20_gal_to_currency': 0.0271,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 3.334,
            'nox_lb_to_currency': 3.334,
            'pm10_lb_to_currency': 2.84,
            'sox_lb_to_currency': 2.06,
            'voc_lb_to_currency': 3.75
        }
    },
    'NMtnPrFNL': {
        'name': 'North',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.636,
            'natural_gas_kbtu_to_currency': 0.009066,
            'h20_gal_to_currency': 0.0108,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 2.77,
            'nox_lb_to_currency': 2.77,
            'pm10_lb_to_currency': 0.49,
            'sox_lb_to_currency': 0.98,
            'voc_lb_to_currency': 2.61
        }
    },
    'NoEastXXX': {
        'name': 'Northeast',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.1401,
            'natural_gas_kbtu_to_currency': 0.01408,
            'h20_gal_to_currency': 0.0008,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 4.59,
            'nox_lb_to_currency': 4.59,
            'pm10_lb_to_currency': 8.31,
            'sox_lb_to_currency': 3.48,
            'voc_lb_to_currency': 2.31
        }
    },
    'PacfNWLOG': {
        'name': 'Pacific Northwest',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.0512,
            'natural_gas_kbtu_to_currency': 0.01146,
            'h20_gal_to_currency': 0.02779,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 0.94,
            'nox_lb_to_currency': 0.94,
            'pm10_lb_to_currency': 1.67,
            'sox_lb_to_currency': 1.88,
            'voc_lb_to_currency': 0.35
        }
    },
    'PiedmtCLT': {
        'name': 'South',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.0759,
            'natural_gas_kbtu_to_currency': 0.01046,
            'h20_gal_to_currency': 0.0099,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 6.55,
            'nox_lb_to_currency': 6.55,
            'pm10_lb_to_currency': 2.49,
            'sox_lb_to_currency': 1.97,
            'voc_lb_to_currency': 6.26
        }
    },
    'SoCalCSMA': {
        'name': 'Southern California Coast',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.16281,
            'natural_gas_kbtu_to_currency': 0.0131,
            'h20_gal_to_currency': 0.00183,
            'co2_lb_to_currency': 0.0150,
            'o3_lb_to_currency': 16.44,
            'nox_lb_to_currency': 16.44,
            'pm10_lb_to_currency': 51.32,
            'sox_lb_to_currency': 21.47,
            'voc_lb_to_currency': 3.34
        }
    },
    'SWDsrtGDL': {
        'name': 'Southwest Desert',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.1208,
            'natural_gas_kbtu_to_currency': 0.009409,
            'h20_gal_to_currency': 0.0048,
            'co2_lb_to_currency': 0.0075,
            'o3_lb_to_currency': 4.0,
            'nox_lb_to_currency': 4.0,
            'pm10_lb_to_currency': 6.0,
            'sox_lb_to_currency': 15.7,
            'voc_lb_to_currency': 4.0
        }
    },
    'TpIntWBOI': {
        'name': 'Temperate Interior West',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.060936,
            'natural_gas_kbtu_to_currency': 0.0114245,
            'h20_gal_to_currency': 0.005,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 0.51,
            'nox_lb_to_currency': 0.51,
            'pm10_lb_to_currency': 0.92,
            'sox_lb_to_currency': 0.06,
            'voc_lb_to_currency': 0.14
        }
    },
    'TropicPacXXX': {
        'name': 'Tropical',
        'currency_conversion': {
            'electricity_kwh_to_currency': 0.122,
            'natural_gas_kbtu_to_currency': 0.0235,
            'h20_gal_to_currency': 0.01,
            'co2_lb_to_currency': 0.00334,
            'o3_lb_to_currency': 1.47,
            'nox_lb_to_currency': 1.47,
            'pm10_lb_to_currency': 1.34,
            'sox_lb_to_currency': 1.52,
            'voc_lb_to_currency': 0.60
        }
    }
}


ITREE_REGION_CHOICES = [(code, conf['name']) for code, conf in ITREE_REGIONS.items()]
