# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Something went wrong with your export.'), (0, 'Pending'), (1, 'Query returned no trees or planting sites.'), (2, 'User has no permissions on this model'), (3, 'Ready')], default=0),
        ),
    ]
