# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otm_comments', '0003_auto_20160923_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enhancedthreadedcomment',
            options={},
        ),
    ]
